
#ifndef __ACPEXCTL_I_C__
#define __ACPEXCTL_I_C__

#include "../inc/zacpexctl_i.c"

#ifndef CLSID_AcPeDlgLaunchCtrl
#define CLSID_AcPeDlgLaunchCtrl		CLSID_ZcPeDlgLaunchCtrl
#endif //#ifndef CLSID_AcPeDlgLaunchCtrl

#ifndef CLSID_AcPePick2PointsCtrl
#define CLSID_AcPePick2PointsCtrl		CLSID_ZcPePick2PointsCtrl
#endif //#ifndef CLSID_AcPePick2PointsCtrl

#ifndef CLSID_AcPePropertyEditor
#define CLSID_AcPePropertyEditor		CLSID_ZcPePropertyEditor
#endif //#ifndef CLSID_AcPePropertyEditor

#ifndef CLSID_AcPePropertyEditorACADNumeric
#define CLSID_AcPePropertyEditorACADNumeric		CLSID_ZcPePropertyEditorZCADNumeric
#endif //#ifndef CLSID_AcPePropertyEditorACADNumeric

#ifndef CLSID_AcPePropertyEditorAttributeValue
#define CLSID_AcPePropertyEditorAttributeValue		CLSID_ZcPePropertyEditorAttributeValue
#endif //#ifndef CLSID_AcPePropertyEditorAttributeValue

#ifndef CLSID_AcPePropertyEditorBool
#define CLSID_AcPePropertyEditorBool		CLSID_ZcPePropertyEditorBool
#endif //#ifndef CLSID_AcPePropertyEditorBool

#ifndef CLSID_AcPePropertyEditorColor
#define CLSID_AcPePropertyEditorColor		CLSID_ZcPePropertyEditorColor
#endif //#ifndef CLSID_AcPePropertyEditorColor

#ifndef CLSID_AcPePropertyEditorCustomColor
#define CLSID_AcPePropertyEditorCustomColor		CLSID_ZcPePropertyEditorCustomColor
#endif //#ifndef CLSID_AcPePropertyEditorCustomColor

#ifndef CLSID_AcPePropertyEditorDimArrowHead
#define CLSID_AcPePropertyEditorDimArrowHead		CLSID_ZcPePropertyEditorDimArrowHead
#endif //#ifndef CLSID_AcPePropertyEditorDimArrowHead

#ifndef CLSID_AcPePropertyEditorDimStyle
#define CLSID_AcPePropertyEditorDimStyle		CLSID_ZcPePropertyEditorDimStyle
#endif //#ifndef CLSID_AcPePropertyEditorDimStyle

#ifndef CLSID_AcPePropertyEditorEditButton
#define CLSID_AcPePropertyEditorEditButton		CLSID_ZcPePropertyEditorEditButton
#endif //#ifndef CLSID_AcPePropertyEditorEditButton

#ifndef CLSID_AcPePropertyEditorEllipseEndAngle
#define CLSID_AcPePropertyEditorEllipseEndAngle		CLSID_ZcPePropertyEditorEllipseEndAngle
#endif //#ifndef CLSID_AcPePropertyEditorEllipseEndAngle

#ifndef CLSID_AcPePropertyEditorEllipses
#define CLSID_AcPePropertyEditorEllipses		CLSID_ZcPePropertyEditorEllipses
#endif //#ifndef CLSID_AcPePropertyEditorEllipses

#ifndef CLSID_AcPePropertyEditorEllipsesHyperlinks
#define CLSID_AcPePropertyEditorEllipsesHyperlinks		CLSID_ZcPePropertyEditorEllipsesHyperlinks
#endif //#ifndef CLSID_AcPePropertyEditorEllipsesHyperlinks

#ifndef CLSID_AcPePropertyEditorEllipsisHatchPatternType
#define CLSID_AcPePropertyEditorEllipsisHatchPatternType		CLSID_ZcPePropertyEditorEllipsisHatchPatternType
#endif //#ifndef CLSID_AcPePropertyEditorEllipsisHatchPatternType

#ifndef CLSID_AcPePropertyEditorEnum
#define CLSID_AcPePropertyEditorEnum		CLSID_ZcPePropertyEditorEnum
#endif //#ifndef CLSID_AcPePropertyEditorEnum

#ifndef CLSID_AcPePropertyEditorGradientPattern
#define CLSID_AcPePropertyEditorGradientPattern		CLSID_ZcPePropertyEditorGradientPattern
#endif //#ifndef CLSID_AcPePropertyEditorGradientPattern

#ifndef CLSID_AcPePropertyEditorHatchEnum
#define CLSID_AcPePropertyEditorHatchEnum		CLSID_ZcPePropertyEditorHatchEnum
#endif //#ifndef CLSID_AcPePropertyEditorHatchEnum

#ifndef CLSID_AcPePropertyEditorHatchISOPenWidth
#define CLSID_AcPePropertyEditorHatchISOPenWidth		CLSID_ZcPePropertyEditorHatchISOPenWidth
#endif //#ifndef CLSID_AcPePropertyEditorHatchISOPenWidth

#ifndef CLSID_AcPePropertyEditorHatchPatternName
#define CLSID_AcPePropertyEditorHatchPatternName		CLSID_ZcPePropertyEditorHatchPatternName
#endif //#ifndef CLSID_AcPePropertyEditorHatchPatternName

#ifndef CLSID_AcPePropertyEditorLType
#define CLSID_AcPePropertyEditorLType		CLSID_ZcPePropertyEditorLType
#endif //#ifndef CLSID_AcPePropertyEditorLType

#ifndef CLSID_AcPePropertyEditorLWeight
#define CLSID_AcPePropertyEditorLWeight		CLSID_ZcPePropertyEditorLWeight
#endif //#ifndef CLSID_AcPePropertyEditorLWeight

#ifndef CLSID_AcPePropertyEditorLayer
#define CLSID_AcPePropertyEditorLayer		CLSID_ZcPePropertyEditorLayer
#endif //#ifndef CLSID_AcPePropertyEditorLayer

#ifndef CLSID_AcPePropertyEditorLightIntensity
#define CLSID_AcPePropertyEditorLightIntensity		CLSID_ZcPePropertyEditorLightIntensity
#endif //#ifndef CLSID_AcPePropertyEditorLightIntensity

#ifndef CLSID_AcPePropertyEditorLightLampColor
#define CLSID_AcPePropertyEditorLightLampColor		CLSID_ZcPePropertyEditorLightLampColor
#endif //#ifndef CLSID_AcPePropertyEditorLightLampColor

#ifndef CLSID_AcPePropertyEditorLightWebPreview
#define CLSID_AcPePropertyEditorLightWebPreview		CLSID_ZcPePropertyEditorLightWebPreview
#endif //#ifndef CLSID_AcPePropertyEditorLightWebPreview

#ifndef CLSID_AcPePropertyEditorMLeaderStyle
#define CLSID_AcPePropertyEditorMLeaderStyle		CLSID_ZcPePropertyEditorMLeaderStyle
#endif //#ifndef CLSID_AcPePropertyEditorMLeaderStyle

#ifndef CLSID_AcPePropertyEditorMTextDir
#define CLSID_AcPePropertyEditorMTextDir		CLSID_ZcPePropertyEditorMTextDir
#endif //#ifndef CLSID_AcPePropertyEditorMTextDir

#ifndef CLSID_AcPePropertyEditorMTextStyle
#define CLSID_AcPePropertyEditorMTextStyle		CLSID_ZcPePropertyEditorMTextStyle
#endif //#ifndef CLSID_AcPePropertyEditorMTextStyle

#ifndef CLSID_AcPePropertyEditorMaterial
#define CLSID_AcPePropertyEditorMaterial		CLSID_ZcPePropertyEditorMaterial
#endif //#ifndef CLSID_AcPePropertyEditorMaterial

#ifndef CLSID_AcPePropertyEditorNoPickVariant
#define CLSID_AcPePropertyEditorNoPickVariant		CLSID_ZcPePropertyEditorNoPickVariant
#endif //#ifndef CLSID_AcPePropertyEditorNoPickVariant

#ifndef CLSID_AcPePropertyEditorNumeric
#define CLSID_AcPePropertyEditorNumeric		CLSID_ZcPePropertyEditorNumeric
#endif //#ifndef CLSID_AcPePropertyEditorNumeric

#ifndef CLSID_AcPePropertyEditorNumericArea
#define CLSID_AcPePropertyEditorNumericArea		CLSID_ZcPePropertyEditorNumericArea
#endif //#ifndef CLSID_AcPePropertyEditorNumericArea

#ifndef CLSID_AcPePropertyEditorPlotStyleName
#define CLSID_AcPePropertyEditorPlotStyleName		CLSID_ZcPePropertyEditorPlotStyleName
#endif //#ifndef CLSID_AcPePropertyEditorPlotStyleName

#ifndef CLSID_AcPePropertyEditorPlotStyleTable
#define CLSID_AcPePropertyEditorPlotStyleTable		CLSID_ZcPePropertyEditorPlotStyleTable
#endif //#ifndef CLSID_AcPePropertyEditorPlotStyleTable

#ifndef CLSID_AcPePropertyEditorPredefBlock
#define CLSID_AcPePropertyEditorPredefBlock		CLSID_ZcPePropertyEditorPredefBlock
#endif //#ifndef CLSID_AcPePropertyEditorPredefBlock

#ifndef CLSID_AcPePropertyEditorPwdText
#define CLSID_AcPePropertyEditorPwdText		CLSID_ZcPePropertyEditorPwdText
#endif //#ifndef CLSID_AcPePropertyEditorPwdText

#ifndef CLSID_AcPePropertyEditorRasterImageHeight
#define CLSID_AcPePropertyEditorRasterImageHeight		CLSID_ZcPePropertyEditorRasterImageHeight
#endif //#ifndef CLSID_AcPePropertyEditorRasterImageHeight

#ifndef CLSID_AcPePropertyEditorRasterImageWidth
#define CLSID_AcPePropertyEditorRasterImageWidth		CLSID_ZcPePropertyEditorRasterImageWidth
#endif //#ifndef CLSID_AcPePropertyEditorRasterImageWidth

#ifndef CLSID_AcPePropertyEditorSpin
#define CLSID_AcPePropertyEditorSpin		CLSID_ZcPePropertyEditorSpin
#endif //#ifndef CLSID_AcPePropertyEditorSpin

#ifndef CLSID_AcPePropertyEditorTableStyle
#define CLSID_AcPePropertyEditorTableStyle		CLSID_ZcPePropertyEditorTableStyle
#endif //#ifndef CLSID_AcPePropertyEditorTableStyle

#ifndef CLSID_AcPePropertyEditorText
#define CLSID_AcPePropertyEditorText		CLSID_ZcPePropertyEditorText
#endif //#ifndef CLSID_AcPePropertyEditorText

#ifndef CLSID_AcPePropertyEditorTextEx
#define CLSID_AcPePropertyEditorTextEx		CLSID_ZcPePropertyEditorTextEx
#endif //#ifndef CLSID_AcPePropertyEditorTextEx

#ifndef CLSID_AcPePropertyEditorTextJustify
#define CLSID_AcPePropertyEditorTextJustify		CLSID_ZcPePropertyEditorTextJustify
#endif //#ifndef CLSID_AcPePropertyEditorTextJustify

#ifndef CLSID_AcPePropertyEditorTextStyle
#define CLSID_AcPePropertyEditorTextStyle		CLSID_ZcPePropertyEditorTextStyle
#endif //#ifndef CLSID_AcPePropertyEditorTextStyle

#ifndef CLSID_AcPePropertyEditorVariant
#define CLSID_AcPePropertyEditorVariant		CLSID_ZcPePropertyEditorVariant
#endif //#ifndef CLSID_AcPePropertyEditorVariant

#ifndef CLSID_AcPePropertyEditorVisualStyle
#define CLSID_AcPePropertyEditorVisualStyle		CLSID_ZcPePropertyEditorVisualStyle
#endif //#ifndef CLSID_AcPePropertyEditorVisualStyle

#ifndef CLSID_AcPePropertyEditorZCADNumeric
#define CLSID_AcPePropertyEditorZCADNumeric		CLSID_ZcPePropertyEditorZCADNumeric
#endif //#ifndef CLSID_AcPePropertyEditorZCADNumeric

#ifndef IID_IAcPeButtonEditCtrl
#define IID_IAcPeButtonEditCtrl		IID_IZcPeButtonEditCtrl
#endif //#ifndef IID_IAcPeButtonEditCtrl

#ifndef IID_IAcPeButtonPicture
#define IID_IAcPeButtonPicture		IID_IZcPeButtonPicture
#endif //#ifndef IID_IAcPeButtonPicture

#ifndef IID_IAcPeCalculatorCtrl
#define IID_IAcPeCalculatorCtrl		IID_IZcPeCalculatorCtrl
#endif //#ifndef IID_IAcPeCalculatorCtrl

#ifndef IID_IAcPeColorCtrl
#define IID_IAcPeColorCtrl		IID_IZcPeColorCtrl
#endif //#ifndef IID_IAcPeColorCtrl

#ifndef IID_IAcPeNoPickVariantRW
#define IID_IAcPeNoPickVariantRW		IID_IZcPeNoPickVariantRW
#endif //#ifndef IID_IAcPeNoPickVariantRW

#ifndef IID_IAcPeNumericEditor
#define IID_IAcPeNumericEditor		IID_IZcPeNumericEditor
#endif //#ifndef IID_IAcPeNumericEditor

#ifndef IID_IAcPePick2PointsCtrl
#define IID_IAcPePick2PointsCtrl		IID_IZcPePick2PointsCtrl
#endif //#ifndef IID_IAcPePick2PointsCtrl

#ifndef IID_IAcPeSpinCtrl
#define IID_IAcPeSpinCtrl		IID_IZcPeSpinCtrl
#endif //#ifndef IID_IAcPeSpinCtrl

#ifndef IID_IAcPeVariantCtrl
#define IID_IAcPeVariantCtrl		IID_IZcPeVariantCtrl
#endif //#ifndef IID_IAcPeVariantCtrl

#endif //#ifndef __ACPEXCTL_I_C__
