
#ifndef __ACPEXCTL_H__
#define __ACPEXCTL_H__

#include "../inc/zacpexctl.h"

#ifndef AcPeDlgLaunchCtrl
#define AcPeDlgLaunchCtrl		ZcPeDlgLaunchCtrl
#endif //#ifndef AcPeDlgLaunchCtrl

#ifndef AcPeNumericType
#define AcPeNumericType		ZcPeNumericType
#endif //#ifndef AcPeNumericType

#ifndef AcPePick2PointsCtrl
#define AcPePick2PointsCtrl		ZcPePick2PointsCtrl
#endif //#ifndef AcPePick2PointsCtrl

#ifndef AcPePropertyEditorACADNumeric
#define AcPePropertyEditorACADNumeric		ZcPePropertyEditorZCADNumeric
#endif //#ifndef AcPePropertyEditorACADNumeric

#ifndef AcPePropertyEditorAttributeValue
#define AcPePropertyEditorAttributeValue		ZcPePropertyEditorAttributeValue
#endif //#ifndef AcPePropertyEditorAttributeValue

#ifndef AcPePropertyEditorBool
#define AcPePropertyEditorBool		ZcPePropertyEditorBool
#endif //#ifndef AcPePropertyEditorBool

#ifndef AcPePropertyEditorColor
#define AcPePropertyEditorColor		ZcPePropertyEditorColor
#endif //#ifndef AcPePropertyEditorColor

#ifndef AcPePropertyEditorCustomColor
#define AcPePropertyEditorCustomColor		ZcPePropertyEditorCustomColor
#endif //#ifndef AcPePropertyEditorCustomColor

#ifndef AcPePropertyEditorDimArrowHead
#define AcPePropertyEditorDimArrowHead		ZcPePropertyEditorDimArrowHead
#endif //#ifndef AcPePropertyEditorDimArrowHead

#ifndef AcPePropertyEditorDimStyle
#define AcPePropertyEditorDimStyle		ZcPePropertyEditorDimStyle
#endif //#ifndef AcPePropertyEditorDimStyle

#ifndef AcPePropertyEditorEditButton
#define AcPePropertyEditorEditButton		ZcPePropertyEditorEditButton
#endif //#ifndef AcPePropertyEditorEditButton

#ifndef AcPePropertyEditorEllipseEndAngle
#define AcPePropertyEditorEllipseEndAngle		ZcPePropertyEditorEllipseEndAngle
#endif //#ifndef AcPePropertyEditorEllipseEndAngle

#ifndef AcPePropertyEditorEllipses
#define AcPePropertyEditorEllipses		ZcPePropertyEditorEllipses
#endif //#ifndef AcPePropertyEditorEllipses

#ifndef AcPePropertyEditorEllipsesHyperlinks
#define AcPePropertyEditorEllipsesHyperlinks		ZcPePropertyEditorEllipsesHyperlinks
#endif //#ifndef AcPePropertyEditorEllipsesHyperlinks

#ifndef AcPePropertyEditorEllipsisHatchPatternType
#define AcPePropertyEditorEllipsisHatchPatternType		ZcPePropertyEditorEllipsisHatchPatternType
#endif //#ifndef AcPePropertyEditorEllipsisHatchPatternType

#ifndef AcPePropertyEditorEnum
#define AcPePropertyEditorEnum		ZcPePropertyEditorEnum
#endif //#ifndef AcPePropertyEditorEnum

#ifndef AcPePropertyEditorGradientPattern
#define AcPePropertyEditorGradientPattern		ZcPePropertyEditorGradientPattern
#endif //#ifndef AcPePropertyEditorGradientPattern

#ifndef AcPePropertyEditorHatchEnum
#define AcPePropertyEditorHatchEnum		ZcPePropertyEditorHatchEnum
#endif //#ifndef AcPePropertyEditorHatchEnum

#ifndef AcPePropertyEditorHatchISOPenWidth
#define AcPePropertyEditorHatchISOPenWidth		ZcPePropertyEditorHatchISOPenWidth
#endif //#ifndef AcPePropertyEditorHatchISOPenWidth

#ifndef AcPePropertyEditorHatchPatternName
#define AcPePropertyEditorHatchPatternName		ZcPePropertyEditorHatchPatternName
#endif //#ifndef AcPePropertyEditorHatchPatternName

#ifndef AcPePropertyEditorLType
#define AcPePropertyEditorLType		ZcPePropertyEditorLType
#endif //#ifndef AcPePropertyEditorLType

#ifndef AcPePropertyEditorLWeight
#define AcPePropertyEditorLWeight		ZcPePropertyEditorLWeight
#endif //#ifndef AcPePropertyEditorLWeight

#ifndef AcPePropertyEditorLayer
#define AcPePropertyEditorLayer		ZcPePropertyEditorLayer
#endif //#ifndef AcPePropertyEditorLayer

#ifndef AcPePropertyEditorLightIntensity
#define AcPePropertyEditorLightIntensity		ZcPePropertyEditorLightIntensity
#endif //#ifndef AcPePropertyEditorLightIntensity

#ifndef AcPePropertyEditorLightLampColor
#define AcPePropertyEditorLightLampColor		ZcPePropertyEditorLightLampColor
#endif //#ifndef AcPePropertyEditorLightLampColor

#ifndef AcPePropertyEditorLightWebPreview
#define AcPePropertyEditorLightWebPreview		ZcPePropertyEditorLightWebPreview
#endif //#ifndef AcPePropertyEditorLightWebPreview

#ifndef AcPePropertyEditorMLeaderStyle
#define AcPePropertyEditorMLeaderStyle		ZcPePropertyEditorMLeaderStyle
#endif //#ifndef AcPePropertyEditorMLeaderStyle

#ifndef AcPePropertyEditorMTextDir
#define AcPePropertyEditorMTextDir		ZcPePropertyEditorMTextDir
#endif //#ifndef AcPePropertyEditorMTextDir

#ifndef AcPePropertyEditorMTextStyle
#define AcPePropertyEditorMTextStyle		ZcPePropertyEditorMTextStyle
#endif //#ifndef AcPePropertyEditorMTextStyle

#ifndef AcPePropertyEditorMaterial
#define AcPePropertyEditorMaterial		ZcPePropertyEditorMaterial
#endif //#ifndef AcPePropertyEditorMaterial

#ifndef AcPePropertyEditorNoPickVariant
#define AcPePropertyEditorNoPickVariant		ZcPePropertyEditorNoPickVariant
#endif //#ifndef AcPePropertyEditorNoPickVariant

#ifndef AcPePropertyEditorNumeric
#define AcPePropertyEditorNumeric		ZcPePropertyEditorNumeric
#endif //#ifndef AcPePropertyEditorNumeric

#ifndef AcPePropertyEditorNumericArea
#define AcPePropertyEditorNumericArea		ZcPePropertyEditorNumericArea
#endif //#ifndef AcPePropertyEditorNumericArea

#ifndef AcPePropertyEditorPlotStyleName
#define AcPePropertyEditorPlotStyleName		ZcPePropertyEditorPlotStyleName
#endif //#ifndef AcPePropertyEditorPlotStyleName

#ifndef AcPePropertyEditorPlotStyleTable
#define AcPePropertyEditorPlotStyleTable		ZcPePropertyEditorPlotStyleTable
#endif //#ifndef AcPePropertyEditorPlotStyleTable

#ifndef AcPePropertyEditorPredefBlock
#define AcPePropertyEditorPredefBlock		ZcPePropertyEditorPredefBlock
#endif //#ifndef AcPePropertyEditorPredefBlock

#ifndef AcPePropertyEditorPwdText
#define AcPePropertyEditorPwdText		ZcPePropertyEditorPwdText
#endif //#ifndef AcPePropertyEditorPwdText

#ifndef AcPePropertyEditorRasterImageHeight
#define AcPePropertyEditorRasterImageHeight		ZcPePropertyEditorRasterImageHeight
#endif //#ifndef AcPePropertyEditorRasterImageHeight

#ifndef AcPePropertyEditorRasterImageWidth
#define AcPePropertyEditorRasterImageWidth		ZcPePropertyEditorRasterImageWidth
#endif //#ifndef AcPePropertyEditorRasterImageWidth

#ifndef AcPePropertyEditorSpin
#define AcPePropertyEditorSpin		ZcPePropertyEditorSpin
#endif //#ifndef AcPePropertyEditorSpin

#ifndef AcPePropertyEditorTableStyle
#define AcPePropertyEditorTableStyle		ZcPePropertyEditorTableStyle
#endif //#ifndef AcPePropertyEditorTableStyle

#ifndef AcPePropertyEditorText
#define AcPePropertyEditorText		ZcPePropertyEditorText
#endif //#ifndef AcPePropertyEditorText

#ifndef AcPePropertyEditorTextEx
#define AcPePropertyEditorTextEx		ZcPePropertyEditorTextEx
#endif //#ifndef AcPePropertyEditorTextEx

#ifndef AcPePropertyEditorTextJustify
#define AcPePropertyEditorTextJustify		ZcPePropertyEditorTextJustify
#endif //#ifndef AcPePropertyEditorTextJustify

#ifndef AcPePropertyEditorTextStyle
#define AcPePropertyEditorTextStyle		ZcPePropertyEditorTextStyle
#endif //#ifndef AcPePropertyEditorTextStyle

#ifndef AcPePropertyEditorVariant
#define AcPePropertyEditorVariant		ZcPePropertyEditorVariant
#endif //#ifndef AcPePropertyEditorVariant

#ifndef AcPePropertyEditorVisualStyle
#define AcPePropertyEditorVisualStyle		ZcPePropertyEditorVisualStyle
#endif //#ifndef AcPePropertyEditorVisualStyle

#ifndef CLSID_AcPeDlgLaunchCtrl
#define CLSID_AcPeDlgLaunchCtrl		CLSID_ZcPeDlgLaunchCtrl
#endif //#ifndef CLSID_AcPeDlgLaunchCtrl

#ifndef CLSID_AcPePick2PointsCtrl
#define CLSID_AcPePick2PointsCtrl		CLSID_ZcPePick2PointsCtrl
#endif //#ifndef CLSID_AcPePick2PointsCtrl

#ifndef CLSID_AcPePropertyEditor
#define CLSID_AcPePropertyEditor		CLSID_ZcPePropertyEditor
#endif //#ifndef CLSID_AcPePropertyEditor

#ifndef CLSID_AcPePropertyEditorACADNumeric
#define CLSID_AcPePropertyEditorACADNumeric		CLSID_ZcPePropertyEditorZCADNumeric
#endif //#ifndef CLSID_AcPePropertyEditorACADNumeric

#ifndef CLSID_AcPePropertyEditorAttributeValue
#define CLSID_AcPePropertyEditorAttributeValue		CLSID_ZcPePropertyEditorAttributeValue
#endif //#ifndef CLSID_AcPePropertyEditorAttributeValue

#ifndef CLSID_AcPePropertyEditorBool
#define CLSID_AcPePropertyEditorBool		CLSID_ZcPePropertyEditorBool
#endif //#ifndef CLSID_AcPePropertyEditorBool

#ifndef CLSID_AcPePropertyEditorColor
#define CLSID_AcPePropertyEditorColor		CLSID_ZcPePropertyEditorColor
#endif //#ifndef CLSID_AcPePropertyEditorColor

#ifndef CLSID_AcPePropertyEditorCustomColor
#define CLSID_AcPePropertyEditorCustomColor		CLSID_ZcPePropertyEditorCustomColor
#endif //#ifndef CLSID_AcPePropertyEditorCustomColor

#ifndef CLSID_AcPePropertyEditorDimArrowHead
#define CLSID_AcPePropertyEditorDimArrowHead		CLSID_ZcPePropertyEditorDimArrowHead
#endif //#ifndef CLSID_AcPePropertyEditorDimArrowHead

#ifndef CLSID_AcPePropertyEditorDimStyle
#define CLSID_AcPePropertyEditorDimStyle		CLSID_ZcPePropertyEditorDimStyle
#endif //#ifndef CLSID_AcPePropertyEditorDimStyle

#ifndef CLSID_AcPePropertyEditorEditButton
#define CLSID_AcPePropertyEditorEditButton		CLSID_ZcPePropertyEditorEditButton
#endif //#ifndef CLSID_AcPePropertyEditorEditButton

#ifndef CLSID_AcPePropertyEditorEllipseEndAngle
#define CLSID_AcPePropertyEditorEllipseEndAngle		CLSID_ZcPePropertyEditorEllipseEndAngle
#endif //#ifndef CLSID_AcPePropertyEditorEllipseEndAngle

#ifndef CLSID_AcPePropertyEditorEllipses
#define CLSID_AcPePropertyEditorEllipses		CLSID_ZcPePropertyEditorEllipses
#endif //#ifndef CLSID_AcPePropertyEditorEllipses

#ifndef CLSID_AcPePropertyEditorEllipsesHyperlinks
#define CLSID_AcPePropertyEditorEllipsesHyperlinks		CLSID_ZcPePropertyEditorEllipsesHyperlinks
#endif //#ifndef CLSID_AcPePropertyEditorEllipsesHyperlinks

#ifndef CLSID_AcPePropertyEditorEllipsisHatchPatternType
#define CLSID_AcPePropertyEditorEllipsisHatchPatternType		CLSID_ZcPePropertyEditorEllipsisHatchPatternType
#endif //#ifndef CLSID_AcPePropertyEditorEllipsisHatchPatternType

#ifndef CLSID_AcPePropertyEditorEnum
#define CLSID_AcPePropertyEditorEnum		CLSID_ZcPePropertyEditorEnum
#endif //#ifndef CLSID_AcPePropertyEditorEnum

#ifndef CLSID_AcPePropertyEditorGradientPattern
#define CLSID_AcPePropertyEditorGradientPattern		CLSID_ZcPePropertyEditorGradientPattern
#endif //#ifndef CLSID_AcPePropertyEditorGradientPattern

#ifndef CLSID_AcPePropertyEditorHatchEnum
#define CLSID_AcPePropertyEditorHatchEnum		CLSID_ZcPePropertyEditorHatchEnum
#endif //#ifndef CLSID_AcPePropertyEditorHatchEnum

#ifndef CLSID_AcPePropertyEditorHatchISOPenWidth
#define CLSID_AcPePropertyEditorHatchISOPenWidth		CLSID_ZcPePropertyEditorHatchISOPenWidth
#endif //#ifndef CLSID_AcPePropertyEditorHatchISOPenWidth

#ifndef CLSID_AcPePropertyEditorHatchPatternName
#define CLSID_AcPePropertyEditorHatchPatternName		CLSID_ZcPePropertyEditorHatchPatternName
#endif //#ifndef CLSID_AcPePropertyEditorHatchPatternName

#ifndef CLSID_AcPePropertyEditorLType
#define CLSID_AcPePropertyEditorLType		CLSID_ZcPePropertyEditorLType
#endif //#ifndef CLSID_AcPePropertyEditorLType

#ifndef CLSID_AcPePropertyEditorLWeight
#define CLSID_AcPePropertyEditorLWeight		CLSID_ZcPePropertyEditorLWeight
#endif //#ifndef CLSID_AcPePropertyEditorLWeight

#ifndef CLSID_AcPePropertyEditorLayer
#define CLSID_AcPePropertyEditorLayer		CLSID_ZcPePropertyEditorLayer
#endif //#ifndef CLSID_AcPePropertyEditorLayer

#ifndef CLSID_AcPePropertyEditorLightIntensity
#define CLSID_AcPePropertyEditorLightIntensity		CLSID_ZcPePropertyEditorLightIntensity
#endif //#ifndef CLSID_AcPePropertyEditorLightIntensity

#ifndef CLSID_AcPePropertyEditorLightLampColor
#define CLSID_AcPePropertyEditorLightLampColor		CLSID_ZcPePropertyEditorLightLampColor
#endif //#ifndef CLSID_AcPePropertyEditorLightLampColor

#ifndef CLSID_AcPePropertyEditorLightWebPreview
#define CLSID_AcPePropertyEditorLightWebPreview		CLSID_ZcPePropertyEditorLightWebPreview
#endif //#ifndef CLSID_AcPePropertyEditorLightWebPreview

#ifndef CLSID_AcPePropertyEditorMLeaderStyle
#define CLSID_AcPePropertyEditorMLeaderStyle		CLSID_ZcPePropertyEditorMLeaderStyle
#endif //#ifndef CLSID_AcPePropertyEditorMLeaderStyle

#ifndef CLSID_AcPePropertyEditorMTextDir
#define CLSID_AcPePropertyEditorMTextDir		CLSID_ZcPePropertyEditorMTextDir
#endif //#ifndef CLSID_AcPePropertyEditorMTextDir

#ifndef CLSID_AcPePropertyEditorMTextStyle
#define CLSID_AcPePropertyEditorMTextStyle		CLSID_ZcPePropertyEditorMTextStyle
#endif //#ifndef CLSID_AcPePropertyEditorMTextStyle

#ifndef CLSID_AcPePropertyEditorMaterial
#define CLSID_AcPePropertyEditorMaterial		CLSID_ZcPePropertyEditorMaterial
#endif //#ifndef CLSID_AcPePropertyEditorMaterial

#ifndef CLSID_AcPePropertyEditorNoPickVariant
#define CLSID_AcPePropertyEditorNoPickVariant		CLSID_ZcPePropertyEditorNoPickVariant
#endif //#ifndef CLSID_AcPePropertyEditorNoPickVariant

#ifndef CLSID_AcPePropertyEditorNumeric
#define CLSID_AcPePropertyEditorNumeric		CLSID_ZcPePropertyEditorNumeric
#endif //#ifndef CLSID_AcPePropertyEditorNumeric

#ifndef CLSID_AcPePropertyEditorNumericArea
#define CLSID_AcPePropertyEditorNumericArea		CLSID_ZcPePropertyEditorNumericArea
#endif //#ifndef CLSID_AcPePropertyEditorNumericArea

#ifndef CLSID_AcPePropertyEditorPlotStyleName
#define CLSID_AcPePropertyEditorPlotStyleName		CLSID_ZcPePropertyEditorPlotStyleName
#endif //#ifndef CLSID_AcPePropertyEditorPlotStyleName

#ifndef CLSID_AcPePropertyEditorPlotStyleTable
#define CLSID_AcPePropertyEditorPlotStyleTable		CLSID_ZcPePropertyEditorPlotStyleTable
#endif //#ifndef CLSID_AcPePropertyEditorPlotStyleTable

#ifndef CLSID_AcPePropertyEditorPredefBlock
#define CLSID_AcPePropertyEditorPredefBlock		CLSID_ZcPePropertyEditorPredefBlock
#endif //#ifndef CLSID_AcPePropertyEditorPredefBlock

#ifndef CLSID_AcPePropertyEditorPwdText
#define CLSID_AcPePropertyEditorPwdText		CLSID_ZcPePropertyEditorPwdText
#endif //#ifndef CLSID_AcPePropertyEditorPwdText

#ifndef CLSID_AcPePropertyEditorRasterImageHeight
#define CLSID_AcPePropertyEditorRasterImageHeight		CLSID_ZcPePropertyEditorRasterImageHeight
#endif //#ifndef CLSID_AcPePropertyEditorRasterImageHeight

#ifndef CLSID_AcPePropertyEditorRasterImageWidth
#define CLSID_AcPePropertyEditorRasterImageWidth		CLSID_ZcPePropertyEditorRasterImageWidth
#endif //#ifndef CLSID_AcPePropertyEditorRasterImageWidth

#ifndef CLSID_AcPePropertyEditorSpin
#define CLSID_AcPePropertyEditorSpin		CLSID_ZcPePropertyEditorSpin
#endif //#ifndef CLSID_AcPePropertyEditorSpin

#ifndef CLSID_AcPePropertyEditorTableStyle
#define CLSID_AcPePropertyEditorTableStyle		CLSID_ZcPePropertyEditorTableStyle
#endif //#ifndef CLSID_AcPePropertyEditorTableStyle

#ifndef CLSID_AcPePropertyEditorText
#define CLSID_AcPePropertyEditorText		CLSID_ZcPePropertyEditorText
#endif //#ifndef CLSID_AcPePropertyEditorText

#ifndef CLSID_AcPePropertyEditorTextEx
#define CLSID_AcPePropertyEditorTextEx		CLSID_ZcPePropertyEditorTextEx
#endif //#ifndef CLSID_AcPePropertyEditorTextEx

#ifndef CLSID_AcPePropertyEditorTextJustify
#define CLSID_AcPePropertyEditorTextJustify		CLSID_ZcPePropertyEditorTextJustify
#endif //#ifndef CLSID_AcPePropertyEditorTextJustify

#ifndef CLSID_AcPePropertyEditorTextStyle
#define CLSID_AcPePropertyEditorTextStyle		CLSID_ZcPePropertyEditorTextStyle
#endif //#ifndef CLSID_AcPePropertyEditorTextStyle

#ifndef CLSID_AcPePropertyEditorVariant
#define CLSID_AcPePropertyEditorVariant		CLSID_ZcPePropertyEditorVariant
#endif //#ifndef CLSID_AcPePropertyEditorVariant

#ifndef CLSID_AcPePropertyEditorVisualStyle
#define CLSID_AcPePropertyEditorVisualStyle		CLSID_ZcPePropertyEditorVisualStyle
#endif //#ifndef CLSID_AcPePropertyEditorVisualStyle

#ifndef CLSID_AcPePropertyEditorZCADNumeric
#define CLSID_AcPePropertyEditorZCADNumeric		CLSID_ZcPePropertyEditorZCADNumeric
#endif //#ifndef CLSID_AcPePropertyEditorZCADNumeric

#ifndef CLSID_PropertyEditorACADNumeric
#define CLSID_PropertyEditorACADNumeric		CLSID_PropertyEditorZCADNumeric
#endif //#ifndef CLSID_PropertyEditorACADNumeric

#ifndef IAcPeButtonEditCtrl
#define IAcPeButtonEditCtrl		IZcPeButtonEditCtrl
#endif //#ifndef IAcPeButtonEditCtrl

#ifndef IAcPeButtonEditCtrlVtbl
#define IAcPeButtonEditCtrlVtbl		IZcPeButtonEditCtrlVtbl
#endif //#ifndef IAcPeButtonEditCtrlVtbl

#ifndef IAcPeButtonEditCtrl_AddRef
#define IAcPeButtonEditCtrl_AddRef		IZcPeButtonEditCtrl_AddRef
#endif //#ifndef IAcPeButtonEditCtrl_AddRef

#ifndef IAcPeButtonEditCtrl_QueryInterface
#define IAcPeButtonEditCtrl_QueryInterface		IZcPeButtonEditCtrl_QueryInterface
#endif //#ifndef IAcPeButtonEditCtrl_QueryInterface

#ifndef IAcPeButtonEditCtrl_Release
#define IAcPeButtonEditCtrl_Release		IZcPeButtonEditCtrl_Release
#endif //#ifndef IAcPeButtonEditCtrl_Release

#ifndef IAcPeButtonEditCtrl_get_DefaultPicture
#define IAcPeButtonEditCtrl_get_DefaultPicture		IZcPeButtonEditCtrl_get_DefaultPicture
#endif //#ifndef IAcPeButtonEditCtrl_get_DefaultPicture

#ifndef IAcPeButtonEditCtrl_get_DisabledPicture
#define IAcPeButtonEditCtrl_get_DisabledPicture		IZcPeButtonEditCtrl_get_DisabledPicture
#endif //#ifndef IAcPeButtonEditCtrl_get_DisabledPicture

#ifndef IAcPeButtonEditCtrl_put_DefaultPicture
#define IAcPeButtonEditCtrl_put_DefaultPicture		IZcPeButtonEditCtrl_put_DefaultPicture
#endif //#ifndef IAcPeButtonEditCtrl_put_DefaultPicture

#ifndef IAcPeButtonEditCtrl_put_DisabledPicture
#define IAcPeButtonEditCtrl_put_DisabledPicture		IZcPeButtonEditCtrl_put_DisabledPicture
#endif //#ifndef IAcPeButtonEditCtrl_put_DisabledPicture

#ifndef IAcPeButtonPicture
#define IAcPeButtonPicture		IZcPeButtonPicture
#endif //#ifndef IAcPeButtonPicture

#ifndef IAcPeButtonPictureVtbl
#define IAcPeButtonPictureVtbl		IZcPeButtonPictureVtbl
#endif //#ifndef IAcPeButtonPictureVtbl

#ifndef IAcPeButtonPicture_AddRef
#define IAcPeButtonPicture_AddRef		IZcPeButtonPicture_AddRef
#endif //#ifndef IAcPeButtonPicture_AddRef

#ifndef IAcPeButtonPicture_QueryInterface
#define IAcPeButtonPicture_QueryInterface		IZcPeButtonPicture_QueryInterface
#endif //#ifndef IAcPeButtonPicture_QueryInterface

#ifndef IAcPeButtonPicture_Release
#define IAcPeButtonPicture_Release		IZcPeButtonPicture_Release
#endif //#ifndef IAcPeButtonPicture_Release

#ifndef IAcPeButtonPicture_get_DefaultPicture
#define IAcPeButtonPicture_get_DefaultPicture		IZcPeButtonPicture_get_DefaultPicture
#endif //#ifndef IAcPeButtonPicture_get_DefaultPicture

#ifndef IAcPeButtonPicture_get_DisabledPicture
#define IAcPeButtonPicture_get_DisabledPicture		IZcPeButtonPicture_get_DisabledPicture
#endif //#ifndef IAcPeButtonPicture_get_DisabledPicture

#ifndef IAcPeButtonPicture_put_DefaultPicture
#define IAcPeButtonPicture_put_DefaultPicture		IZcPeButtonPicture_put_DefaultPicture
#endif //#ifndef IAcPeButtonPicture_put_DefaultPicture

#ifndef IAcPeButtonPicture_put_DisabledPicture
#define IAcPeButtonPicture_put_DisabledPicture		IZcPeButtonPicture_put_DisabledPicture
#endif //#ifndef IAcPeButtonPicture_put_DisabledPicture

#ifndef IAcPeCalculatorCtrl
#define IAcPeCalculatorCtrl		IZcPeCalculatorCtrl
#endif //#ifndef IAcPeCalculatorCtrl

#ifndef IAcPeCalculatorCtrlVtbl
#define IAcPeCalculatorCtrlVtbl		IZcPeCalculatorCtrlVtbl
#endif //#ifndef IAcPeCalculatorCtrlVtbl

#ifndef IAcPeCalculatorCtrl_AddRef
#define IAcPeCalculatorCtrl_AddRef		IZcPeCalculatorCtrl_AddRef
#endif //#ifndef IAcPeCalculatorCtrl_AddRef

#ifndef IAcPeCalculatorCtrl_QueryInterface
#define IAcPeCalculatorCtrl_QueryInterface		IZcPeCalculatorCtrl_QueryInterface
#endif //#ifndef IAcPeCalculatorCtrl_QueryInterface

#ifndef IAcPeCalculatorCtrl_Release
#define IAcPeCalculatorCtrl_Release		IZcPeCalculatorCtrl_Release
#endif //#ifndef IAcPeCalculatorCtrl_Release

#ifndef IAcPeCalculatorCtrl_SetCalculatorMode
#define IAcPeCalculatorCtrl_SetCalculatorMode		IZcPeCalculatorCtrl_SetCalculatorMode
#endif //#ifndef IAcPeCalculatorCtrl_SetCalculatorMode

#ifndef IAcPeColorCtrl
#define IAcPeColorCtrl		IZcPeColorCtrl
#endif //#ifndef IAcPeColorCtrl

#ifndef IAcPeColorCtrlVtbl
#define IAcPeColorCtrlVtbl		IZcPeColorCtrlVtbl
#endif //#ifndef IAcPeColorCtrlVtbl

#ifndef IAcPeColorCtrl_AddRef
#define IAcPeColorCtrl_AddRef		IZcPeColorCtrl_AddRef
#endif //#ifndef IAcPeColorCtrl_AddRef

#ifndef IAcPeColorCtrl_QueryInterface
#define IAcPeColorCtrl_QueryInterface		IZcPeColorCtrl_QueryInterface
#endif //#ifndef IAcPeColorCtrl_QueryInterface

#ifndef IAcPeColorCtrl_Release
#define IAcPeColorCtrl_Release		IZcPeColorCtrl_Release
#endif //#ifndef IAcPeColorCtrl_Release

#ifndef IAcPeColorCtrl_SetNoMetaColor
#define IAcPeColorCtrl_SetNoMetaColor		IZcPeColorCtrl_SetNoMetaColor
#endif //#ifndef IAcPeColorCtrl_SetNoMetaColor

#ifndef IAcPeNoPickVariantRW
#define IAcPeNoPickVariantRW		IZcPeNoPickVariantRW
#endif //#ifndef IAcPeNoPickVariantRW

#ifndef IAcPeNoPickVariantRWVtbl
#define IAcPeNoPickVariantRWVtbl		IZcPeNoPickVariantRWVtbl
#endif //#ifndef IAcPeNoPickVariantRWVtbl

#ifndef IAcPeNoPickVariantRW_AddRef
#define IAcPeNoPickVariantRW_AddRef		IZcPeNoPickVariantRW_AddRef
#endif //#ifndef IAcPeNoPickVariantRW_AddRef

#ifndef IAcPeNoPickVariantRW_QueryInterface
#define IAcPeNoPickVariantRW_QueryInterface		IZcPeNoPickVariantRW_QueryInterface
#endif //#ifndef IAcPeNoPickVariantRW_QueryInterface

#ifndef IAcPeNoPickVariantRW_Release
#define IAcPeNoPickVariantRW_Release		IZcPeNoPickVariantRW_Release
#endif //#ifndef IAcPeNoPickVariantRW_Release

#ifndef IAcPeNoPickVariantRW_SetAlwaysRW
#define IAcPeNoPickVariantRW_SetAlwaysRW		IZcPeNoPickVariantRW_SetAlwaysRW
#endif //#ifndef IAcPeNoPickVariantRW_SetAlwaysRW

#ifndef IAcPeNumericEditor
#define IAcPeNumericEditor		IZcPeNumericEditor
#endif //#ifndef IAcPeNumericEditor

#ifndef IAcPeNumericEditorVtbl
#define IAcPeNumericEditorVtbl		IZcPeNumericEditorVtbl
#endif //#ifndef IAcPeNumericEditorVtbl

#ifndef IAcPeNumericEditor_AddRef
#define IAcPeNumericEditor_AddRef		IZcPeNumericEditor_AddRef
#endif //#ifndef IAcPeNumericEditor_AddRef

#ifndef IAcPeNumericEditor_QueryInterface
#define IAcPeNumericEditor_QueryInterface		IZcPeNumericEditor_QueryInterface
#endif //#ifndef IAcPeNumericEditor_QueryInterface

#ifndef IAcPeNumericEditor_Release
#define IAcPeNumericEditor_Release		IZcPeNumericEditor_Release
#endif //#ifndef IAcPeNumericEditor_Release

#ifndef IAcPeNumericEditor_SetNumericDataType
#define IAcPeNumericEditor_SetNumericDataType		IZcPeNumericEditor_SetNumericDataType
#endif //#ifndef IAcPeNumericEditor_SetNumericDataType

#ifndef IAcPePick2PointsCtrl
#define IAcPePick2PointsCtrl		IZcPePick2PointsCtrl
#endif //#ifndef IAcPePick2PointsCtrl

#ifndef IAcPePick2PointsCtrlVtbl
#define IAcPePick2PointsCtrlVtbl		IZcPePick2PointsCtrlVtbl
#endif //#ifndef IAcPePick2PointsCtrlVtbl

#ifndef IAcPePick2PointsCtrl_AddRef
#define IAcPePick2PointsCtrl_AddRef		IZcPePick2PointsCtrl_AddRef
#endif //#ifndef IAcPePick2PointsCtrl_AddRef

#ifndef IAcPePick2PointsCtrl_QueryInterface
#define IAcPePick2PointsCtrl_QueryInterface		IZcPePick2PointsCtrl_QueryInterface
#endif //#ifndef IAcPePick2PointsCtrl_QueryInterface

#ifndef IAcPePick2PointsCtrl_Release
#define IAcPePick2PointsCtrl_Release		IZcPePick2PointsCtrl_Release
#endif //#ifndef IAcPePick2PointsCtrl_Release

#ifndef IAcPePick2PointsCtrl_SetPrompts
#define IAcPePick2PointsCtrl_SetPrompts		IZcPePick2PointsCtrl_SetPrompts
#endif //#ifndef IAcPePick2PointsCtrl_SetPrompts

#ifndef IAcPeSpinCtrl
#define IAcPeSpinCtrl		IZcPeSpinCtrl
#endif //#ifndef IAcPeSpinCtrl

#ifndef IAcPeSpinCtrlVtbl
#define IAcPeSpinCtrlVtbl		IZcPeSpinCtrlVtbl
#endif //#ifndef IAcPeSpinCtrlVtbl

#ifndef IAcPeSpinCtrl_AddRef
#define IAcPeSpinCtrl_AddRef		IZcPeSpinCtrl_AddRef
#endif //#ifndef IAcPeSpinCtrl_AddRef

#ifndef IAcPeSpinCtrl_QueryInterface
#define IAcPeSpinCtrl_QueryInterface		IZcPeSpinCtrl_QueryInterface
#endif //#ifndef IAcPeSpinCtrl_QueryInterface

#ifndef IAcPeSpinCtrl_Release
#define IAcPeSpinCtrl_Release		IZcPeSpinCtrl_Release
#endif //#ifndef IAcPeSpinCtrl_Release

#ifndef IAcPeSpinCtrl_SetControls
#define IAcPeSpinCtrl_SetControls		IZcPeSpinCtrl_SetControls
#endif //#ifndef IAcPeSpinCtrl_SetControls

#ifndef IAcPeVariantCtrl
#define IAcPeVariantCtrl		IZcPeVariantCtrl
#endif //#ifndef IAcPeVariantCtrl

#ifndef IAcPeVariantCtrlVtbl
#define IAcPeVariantCtrlVtbl		IZcPeVariantCtrlVtbl
#endif //#ifndef IAcPeVariantCtrlVtbl

#ifndef IAcPeVariantCtrl_AddRef
#define IAcPeVariantCtrl_AddRef		IZcPeVariantCtrl_AddRef
#endif //#ifndef IAcPeVariantCtrl_AddRef

#ifndef IAcPeVariantCtrl_QueryInterface
#define IAcPeVariantCtrl_QueryInterface		IZcPeVariantCtrl_QueryInterface
#endif //#ifndef IAcPeVariantCtrl_QueryInterface

#ifndef IAcPeVariantCtrl_Release
#define IAcPeVariantCtrl_Release		IZcPeVariantCtrl_Release
#endif //#ifndef IAcPeVariantCtrl_Release

#ifndef IAcPeVariantCtrl_SetDwCookies
#define IAcPeVariantCtrl_SetDwCookies		IZcPeVariantCtrl_SetDwCookies
#endif //#ifndef IAcPeVariantCtrl_SetDwCookies

#ifndef IAcPeVariantCtrl_SetElementCount
#define IAcPeVariantCtrl_SetElementCount		IZcPeVariantCtrl_SetElementCount
#endif //#ifndef IAcPeVariantCtrl_SetElementCount

#ifndef IAcPeVariantCtrl_SetGroupOffset
#define IAcPeVariantCtrl_SetGroupOffset		IZcPeVariantCtrl_SetGroupOffset
#endif //#ifndef IAcPeVariantCtrl_SetGroupOffset

#ifndef IID_IAcPeButtonEditCtrl
#define IID_IAcPeButtonEditCtrl		IID_IZcPeButtonEditCtrl
#endif //#ifndef IID_IAcPeButtonEditCtrl

#ifndef IID_IAcPeButtonPicture
#define IID_IAcPeButtonPicture		IID_IZcPeButtonPicture
#endif //#ifndef IID_IAcPeButtonPicture

#ifndef IID_IAcPeCalculatorCtrl
#define IID_IAcPeCalculatorCtrl		IID_IZcPeCalculatorCtrl
#endif //#ifndef IID_IAcPeCalculatorCtrl

#ifndef IID_IAcPeColorCtrl
#define IID_IAcPeColorCtrl		IID_IZcPeColorCtrl
#endif //#ifndef IID_IAcPeColorCtrl

#ifndef IID_IAcPeNoPickVariantRW
#define IID_IAcPeNoPickVariantRW		IID_IZcPeNoPickVariantRW
#endif //#ifndef IID_IAcPeNoPickVariantRW

#ifndef IID_IAcPeNumericEditor
#define IID_IAcPeNumericEditor		IID_IZcPeNumericEditor
#endif //#ifndef IID_IAcPeNumericEditor

#ifndef IID_IAcPePick2PointsCtrl
#define IID_IAcPePick2PointsCtrl		IID_IZcPePick2PointsCtrl
#endif //#ifndef IID_IAcPePick2PointsCtrl

#ifndef IID_IAcPeSpinCtrl
#define IID_IAcPeSpinCtrl		IID_IZcPeSpinCtrl
#endif //#ifndef IID_IAcPeSpinCtrl

#ifndef IID_IAcPeVariantCtrl
#define IID_IAcPeVariantCtrl		IID_IZcPeVariantCtrl
#endif //#ifndef IID_IAcPeVariantCtrl

#ifndef PE_ACAD_ANGLE
#define PE_ACAD_ANGLE		PE_ZCAD_ANGLE
#endif //#ifndef PE_ACAD_ANGLE

#ifndef PE_ACAD_ANGLEPLUS360
#define PE_ACAD_ANGLEPLUS360		PE_ZCAD_ANGLEPLUS360
#endif //#ifndef PE_ACAD_ANGLEPLUS360

#ifndef PE_ACAD_DISTANCE
#define PE_ACAD_DISTANCE		PE_ZCAD_DISTANCE
#endif //#ifndef PE_ACAD_DISTANCE

#ifndef PE_ACAD_NOUNITS
#define PE_ACAD_NOUNITS		PE_ZCAD_NOUNITS
#endif //#ifndef PE_ACAD_NOUNITS

#ifndef PE_ACAD_OTHER
#define PE_ACAD_OTHER		PE_ZCAD_OTHER
#endif //#ifndef PE_ACAD_OTHER

#ifndef PE_ACAD_RAW_ANGLE
#define PE_ACAD_RAW_ANGLE		PE_ZCAD_RAW_ANGLE
#endif //#ifndef PE_ACAD_RAW_ANGLE

#ifndef PE_ACAD_RELATIVE_ANGLE
#define PE_ACAD_RELATIVE_ANGLE		PE_ZCAD_RELATIVE_ANGLE
#endif //#ifndef PE_ACAD_RELATIVE_ANGLE

#ifndef PePropertyEditorACADNumeric
#define PePropertyEditorACADNumeric		PePropertyEditorZCADNumeric
#endif //#ifndef PePropertyEditorACADNumeric

#ifndef ZcPePropertyEditorACADNumeric
#define ZcPePropertyEditorACADNumeric		ZcPePropertyEditorZCADNumeric
#endif //#ifndef ZcPePropertyEditorACADNumeric

#ifndef __AcPeDlgLaunchCtrl_FWD_DEFINED__
#define __AcPeDlgLaunchCtrl_FWD_DEFINED__		__ZcPeDlgLaunchCtrl_FWD_DEFINED__
#endif //#ifndef __AcPeDlgLaunchCtrl_FWD_DEFINED__

#ifndef __AcPePick2PointsCtrl_FWD_DEFINED__
#define __AcPePick2PointsCtrl_FWD_DEFINED__		__ZcPePick2PointsCtrl_FWD_DEFINED__
#endif //#ifndef __AcPePick2PointsCtrl_FWD_DEFINED__

#ifndef __AcPePropertyEditor
#define __AcPePropertyEditor		__ZcPePropertyEditor
#endif //#ifndef __AcPePropertyEditor

#ifndef __AcPePropertyEditorACADNumeric_FWD_DEFINED__
#define __AcPePropertyEditorACADNumeric_FWD_DEFINED__		__ZcPePropertyEditorZCADNumeric_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorACADNumeric_FWD_DEFINED__

#ifndef __AcPePropertyEditorAttributeValue_FWD_DEFINED__
#define __AcPePropertyEditorAttributeValue_FWD_DEFINED__		__ZcPePropertyEditorAttributeValue_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorAttributeValue_FWD_DEFINED__

#ifndef __AcPePropertyEditorBool_FWD_DEFINED__
#define __AcPePropertyEditorBool_FWD_DEFINED__		__ZcPePropertyEditorBool_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorBool_FWD_DEFINED__

#ifndef __AcPePropertyEditorColor_FWD_DEFINED__
#define __AcPePropertyEditorColor_FWD_DEFINED__		__ZcPePropertyEditorColor_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorColor_FWD_DEFINED__

#ifndef __AcPePropertyEditorCustomColor_FWD_DEFINED__
#define __AcPePropertyEditorCustomColor_FWD_DEFINED__		__ZcPePropertyEditorCustomColor_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorCustomColor_FWD_DEFINED__

#ifndef __AcPePropertyEditorDimArrowHead_FWD_DEFINED__
#define __AcPePropertyEditorDimArrowHead_FWD_DEFINED__		__ZcPePropertyEditorDimArrowHead_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorDimArrowHead_FWD_DEFINED__

#ifndef __AcPePropertyEditorDimStyle_FWD_DEFINED__
#define __AcPePropertyEditorDimStyle_FWD_DEFINED__		__ZcPePropertyEditorDimStyle_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorDimStyle_FWD_DEFINED__

#ifndef __AcPePropertyEditorEditButton_FWD_DEFINED__
#define __AcPePropertyEditorEditButton_FWD_DEFINED__		__ZcPePropertyEditorEditButton_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorEditButton_FWD_DEFINED__

#ifndef __AcPePropertyEditorEllipseEndAngle_FWD_DEFINED__
#define __AcPePropertyEditorEllipseEndAngle_FWD_DEFINED__		__ZcPePropertyEditorEllipseEndAngle_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorEllipseEndAngle_FWD_DEFINED__

#ifndef __AcPePropertyEditorEllipsesHyperlinks_FWD_DEFINED__
#define __AcPePropertyEditorEllipsesHyperlinks_FWD_DEFINED__		__ZcPePropertyEditorEllipsesHyperlinks_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorEllipsesHyperlinks_FWD_DEFINED__

#ifndef __AcPePropertyEditorEllipses_FWD_DEFINED__
#define __AcPePropertyEditorEllipses_FWD_DEFINED__		__ZcPePropertyEditorEllipses_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorEllipses_FWD_DEFINED__

#ifndef __AcPePropertyEditorEllipsisHatchPatternType_FWD_DEFINED__
#define __AcPePropertyEditorEllipsisHatchPatternType_FWD_DEFINED__		__ZcPePropertyEditorEllipsisHatchPatternType_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorEllipsisHatchPatternType_FWD_DEFINED__

#ifndef __AcPePropertyEditorEnum_FWD_DEFINED__
#define __AcPePropertyEditorEnum_FWD_DEFINED__		__ZcPePropertyEditorEnum_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorEnum_FWD_DEFINED__

#ifndef __AcPePropertyEditorGradientPattern_FWD_DEFINED__
#define __AcPePropertyEditorGradientPattern_FWD_DEFINED__		__ZcPePropertyEditorGradientPattern_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorGradientPattern_FWD_DEFINED__

#ifndef __AcPePropertyEditorHatchEnum_FWD_DEFINED__
#define __AcPePropertyEditorHatchEnum_FWD_DEFINED__		__ZcPePropertyEditorHatchEnum_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorHatchEnum_FWD_DEFINED__

#ifndef __AcPePropertyEditorHatchISOPenWidth_FWD_DEFINED__
#define __AcPePropertyEditorHatchISOPenWidth_FWD_DEFINED__		__ZcPePropertyEditorHatchISOPenWidth_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorHatchISOPenWidth_FWD_DEFINED__

#ifndef __AcPePropertyEditorHatchPatternName_FWD_DEFINED__
#define __AcPePropertyEditorHatchPatternName_FWD_DEFINED__		__ZcPePropertyEditorHatchPatternName_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorHatchPatternName_FWD_DEFINED__

#ifndef __AcPePropertyEditorLType_FWD_DEFINED__
#define __AcPePropertyEditorLType_FWD_DEFINED__		__ZcPePropertyEditorLType_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorLType_FWD_DEFINED__

#ifndef __AcPePropertyEditorLWeight_FWD_DEFINED__
#define __AcPePropertyEditorLWeight_FWD_DEFINED__		__ZcPePropertyEditorLWeight_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorLWeight_FWD_DEFINED__

#ifndef __AcPePropertyEditorLayer_FWD_DEFINED__
#define __AcPePropertyEditorLayer_FWD_DEFINED__		__ZcPePropertyEditorLayer_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorLayer_FWD_DEFINED__

#ifndef __AcPePropertyEditorLightIntensity_FWD_DEFINED__
#define __AcPePropertyEditorLightIntensity_FWD_DEFINED__		__ZcPePropertyEditorLightIntensity_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorLightIntensity_FWD_DEFINED__

#ifndef __AcPePropertyEditorLightLampColor_FWD_DEFINED__
#define __AcPePropertyEditorLightLampColor_FWD_DEFINED__		__ZcPePropertyEditorLightLampColor_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorLightLampColor_FWD_DEFINED__

#ifndef __AcPePropertyEditorLightWebPreview_FWD_DEFINED__
#define __AcPePropertyEditorLightWebPreview_FWD_DEFINED__		__ZcPePropertyEditorLightWebPreview_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorLightWebPreview_FWD_DEFINED__

#ifndef __AcPePropertyEditorMLeaderStyle_FWD_DEFINED__
#define __AcPePropertyEditorMLeaderStyle_FWD_DEFINED__		__ZcPePropertyEditorMLeaderStyle_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorMLeaderStyle_FWD_DEFINED__

#ifndef __AcPePropertyEditorMTextDir_FWD_DEFINED__
#define __AcPePropertyEditorMTextDir_FWD_DEFINED__		__ZcPePropertyEditorMTextDir_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorMTextDir_FWD_DEFINED__

#ifndef __AcPePropertyEditorMTextStyle_FWD_DEFINED__
#define __AcPePropertyEditorMTextStyle_FWD_DEFINED__		__ZcPePropertyEditorMTextStyle_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorMTextStyle_FWD_DEFINED__

#ifndef __AcPePropertyEditorMaterial_FWD_DEFINED__
#define __AcPePropertyEditorMaterial_FWD_DEFINED__		__ZcPePropertyEditorMaterial_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorMaterial_FWD_DEFINED__

#ifndef __AcPePropertyEditorNoPickVariant_FWD_DEFINED__
#define __AcPePropertyEditorNoPickVariant_FWD_DEFINED__		__ZcPePropertyEditorNoPickVariant_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorNoPickVariant_FWD_DEFINED__

#ifndef __AcPePropertyEditorNumericArea_FWD_DEFINED__
#define __AcPePropertyEditorNumericArea_FWD_DEFINED__		__ZcPePropertyEditorNumericArea_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorNumericArea_FWD_DEFINED__

#ifndef __AcPePropertyEditorNumeric_FWD_DEFINED__
#define __AcPePropertyEditorNumeric_FWD_DEFINED__		__ZcPePropertyEditorNumeric_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorNumeric_FWD_DEFINED__

#ifndef __AcPePropertyEditorPlotStyleName_FWD_DEFINED__
#define __AcPePropertyEditorPlotStyleName_FWD_DEFINED__		__ZcPePropertyEditorPlotStyleName_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorPlotStyleName_FWD_DEFINED__

#ifndef __AcPePropertyEditorPlotStyleTable_FWD_DEFINED__
#define __AcPePropertyEditorPlotStyleTable_FWD_DEFINED__		__ZcPePropertyEditorPlotStyleTable_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorPlotStyleTable_FWD_DEFINED__

#ifndef __AcPePropertyEditorPredefBlock_FWD_DEFINED__
#define __AcPePropertyEditorPredefBlock_FWD_DEFINED__		__ZcPePropertyEditorPredefBlock_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorPredefBlock_FWD_DEFINED__

#ifndef __AcPePropertyEditorPwdText_FWD_DEFINED__
#define __AcPePropertyEditorPwdText_FWD_DEFINED__		__ZcPePropertyEditorPwdText_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorPwdText_FWD_DEFINED__

#ifndef __AcPePropertyEditorRasterImageHeight_FWD_DEFINED__
#define __AcPePropertyEditorRasterImageHeight_FWD_DEFINED__		__ZcPePropertyEditorRasterImageHeight_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorRasterImageHeight_FWD_DEFINED__

#ifndef __AcPePropertyEditorRasterImageWidth_FWD_DEFINED__
#define __AcPePropertyEditorRasterImageWidth_FWD_DEFINED__		__ZcPePropertyEditorRasterImageWidth_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorRasterImageWidth_FWD_DEFINED__

#ifndef __AcPePropertyEditorSpin_FWD_DEFINED__
#define __AcPePropertyEditorSpin_FWD_DEFINED__		__ZcPePropertyEditorSpin_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorSpin_FWD_DEFINED__

#ifndef __AcPePropertyEditorTableStyle_FWD_DEFINED__
#define __AcPePropertyEditorTableStyle_FWD_DEFINED__		__ZcPePropertyEditorTableStyle_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorTableStyle_FWD_DEFINED__

#ifndef __AcPePropertyEditorTextEx_FWD_DEFINED__
#define __AcPePropertyEditorTextEx_FWD_DEFINED__		__ZcPePropertyEditorTextEx_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorTextEx_FWD_DEFINED__

#ifndef __AcPePropertyEditorTextJustify_FWD_DEFINED__
#define __AcPePropertyEditorTextJustify_FWD_DEFINED__		__ZcPePropertyEditorTextJustify_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorTextJustify_FWD_DEFINED__

#ifndef __AcPePropertyEditorTextStyle_FWD_DEFINED__
#define __AcPePropertyEditorTextStyle_FWD_DEFINED__		__ZcPePropertyEditorTextStyle_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorTextStyle_FWD_DEFINED__

#ifndef __AcPePropertyEditorText_FWD_DEFINED__
#define __AcPePropertyEditorText_FWD_DEFINED__		__ZcPePropertyEditorText_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorText_FWD_DEFINED__

#ifndef __AcPePropertyEditorVariant_FWD_DEFINED__
#define __AcPePropertyEditorVariant_FWD_DEFINED__		__ZcPePropertyEditorVariant_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorVariant_FWD_DEFINED__

#ifndef __AcPePropertyEditorVisualStyle_FWD_DEFINED__
#define __AcPePropertyEditorVisualStyle_FWD_DEFINED__		__ZcPePropertyEditorVisualStyle_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorVisualStyle_FWD_DEFINED__

#ifndef __AcPePropertyEditorZCADNumeric_FWD_DEFINED__
#define __AcPePropertyEditorZCADNumeric_FWD_DEFINED__		__ZcPePropertyEditorZCADNumeric_FWD_DEFINED__
#endif //#ifndef __AcPePropertyEditorZCADNumeric_FWD_DEFINED__

#ifndef __IAcPeButtonEditCtrl_FWD_DEFINED__
#define __IAcPeButtonEditCtrl_FWD_DEFINED__		__IZcPeButtonEditCtrl_FWD_DEFINED__
#endif //#ifndef __IAcPeButtonEditCtrl_FWD_DEFINED__

#ifndef __IAcPeButtonEditCtrl_INTERFACE_DEFINED__
#define __IAcPeButtonEditCtrl_INTERFACE_DEFINED__		__IZcPeButtonEditCtrl_INTERFACE_DEFINED__
#endif //#ifndef __IAcPeButtonEditCtrl_INTERFACE_DEFINED__

#ifndef __IAcPeButtonPicture_FWD_DEFINED__
#define __IAcPeButtonPicture_FWD_DEFINED__		__IZcPeButtonPicture_FWD_DEFINED__
#endif //#ifndef __IAcPeButtonPicture_FWD_DEFINED__

#ifndef __IAcPeButtonPicture_INTERFACE_DEFINED__
#define __IAcPeButtonPicture_INTERFACE_DEFINED__		__IZcPeButtonPicture_INTERFACE_DEFINED__
#endif //#ifndef __IAcPeButtonPicture_INTERFACE_DEFINED__

#ifndef __IAcPeCalculatorCtrl_FWD_DEFINED__
#define __IAcPeCalculatorCtrl_FWD_DEFINED__		__IZcPeCalculatorCtrl_FWD_DEFINED__
#endif //#ifndef __IAcPeCalculatorCtrl_FWD_DEFINED__

#ifndef __IAcPeCalculatorCtrl_INTERFACE_DEFINED__
#define __IAcPeCalculatorCtrl_INTERFACE_DEFINED__		__IZcPeCalculatorCtrl_INTERFACE_DEFINED__
#endif //#ifndef __IAcPeCalculatorCtrl_INTERFACE_DEFINED__

#ifndef __IAcPeColorCtrl_FWD_DEFINED__
#define __IAcPeColorCtrl_FWD_DEFINED__		__IZcPeColorCtrl_FWD_DEFINED__
#endif //#ifndef __IAcPeColorCtrl_FWD_DEFINED__

#ifndef __IAcPeColorCtrl_INTERFACE_DEFINED__
#define __IAcPeColorCtrl_INTERFACE_DEFINED__		__IZcPeColorCtrl_INTERFACE_DEFINED__
#endif //#ifndef __IAcPeColorCtrl_INTERFACE_DEFINED__

#ifndef __IAcPeNoPickVariantRW_FWD_DEFINED__
#define __IAcPeNoPickVariantRW_FWD_DEFINED__		__IZcPeNoPickVariantRW_FWD_DEFINED__
#endif //#ifndef __IAcPeNoPickVariantRW_FWD_DEFINED__

#ifndef __IAcPeNoPickVariantRW_INTERFACE_DEFINED__
#define __IAcPeNoPickVariantRW_INTERFACE_DEFINED__		__IZcPeNoPickVariantRW_INTERFACE_DEFINED__
#endif //#ifndef __IAcPeNoPickVariantRW_INTERFACE_DEFINED__

#ifndef __IAcPeNumericEditor_FWD_DEFINED__
#define __IAcPeNumericEditor_FWD_DEFINED__		__IZcPeNumericEditor_FWD_DEFINED__
#endif //#ifndef __IAcPeNumericEditor_FWD_DEFINED__

#ifndef __IAcPeNumericEditor_INTERFACE_DEFINED__
#define __IAcPeNumericEditor_INTERFACE_DEFINED__		__IZcPeNumericEditor_INTERFACE_DEFINED__
#endif //#ifndef __IAcPeNumericEditor_INTERFACE_DEFINED__

#ifndef __IAcPePick2PointsCtrl_FWD_DEFINED__
#define __IAcPePick2PointsCtrl_FWD_DEFINED__		__IZcPePick2PointsCtrl_FWD_DEFINED__
#endif //#ifndef __IAcPePick2PointsCtrl_FWD_DEFINED__

#ifndef __IAcPePick2PointsCtrl_INTERFACE_DEFINED__
#define __IAcPePick2PointsCtrl_INTERFACE_DEFINED__		__IZcPePick2PointsCtrl_INTERFACE_DEFINED__
#endif //#ifndef __IAcPePick2PointsCtrl_INTERFACE_DEFINED__

#ifndef __IAcPeSpinCtrl_FWD_DEFINED__
#define __IAcPeSpinCtrl_FWD_DEFINED__		__IZcPeSpinCtrl_FWD_DEFINED__
#endif //#ifndef __IAcPeSpinCtrl_FWD_DEFINED__

#ifndef __IAcPeSpinCtrl_INTERFACE_DEFINED__
#define __IAcPeSpinCtrl_INTERFACE_DEFINED__		__IZcPeSpinCtrl_INTERFACE_DEFINED__
#endif //#ifndef __IAcPeSpinCtrl_INTERFACE_DEFINED__

#ifndef __IAcPeVariantCtrl_FWD_DEFINED__
#define __IAcPeVariantCtrl_FWD_DEFINED__		__IZcPeVariantCtrl_FWD_DEFINED__
#endif //#ifndef __IAcPeVariantCtrl_FWD_DEFINED__

#ifndef __IAcPeVariantCtrl_INTERFACE_DEFINED__
#define __IAcPeVariantCtrl_INTERFACE_DEFINED__		__IZcPeVariantCtrl_INTERFACE_DEFINED__
#endif //#ifndef __IAcPeVariantCtrl_INTERFACE_DEFINED__

#endif //#ifndef __ACPEXCTL_H__