
#ifndef __ACSTATUSBAR_H__
#define __ACSTATUSBAR_H__

#include "acdocman.h"

#include "../inc/zAcStatusBar.h"

#ifndef ACSBPANE_ANNO_ANNOTATION_SCALE
#define ACSBPANE_ANNO_ANNOTATION_SCALE		ZCSBPANE_ANNO_ANNOTATION_SCALE
#endif //#ifndef ACSBPANE_ANNO_ANNOTATION_SCALE

#ifndef ACSBPANE_ANNO_ANNOTATION_SCALE_LABEL
#define ACSBPANE_ANNO_ANNOTATION_SCALE_LABEL		ZCSBPANE_ANNO_ANNOTATION_SCALE_LABEL
#endif //#ifndef ACSBPANE_ANNO_ANNOTATION_SCALE_LABEL

#ifndef ACSBPANE_ANNO_ANNO_ALL_VISIBLE
#define ACSBPANE_ANNO_ANNO_ALL_VISIBLE		ZCSBPANE_ANNO_ANNO_ALL_VISIBLE
#endif //#ifndef ACSBPANE_ANNO_ANNO_ALL_VISIBLE

#ifndef ACSBPANE_ANNO_AUTOSCALE
#define ACSBPANE_ANNO_AUTOSCALE		ZCSBPANE_ANNO_AUTOSCALE
#endif //#ifndef ACSBPANE_ANNO_AUTOSCALE

#ifndef ACSBPANE_ANNO_EMPTY
#define ACSBPANE_ANNO_EMPTY		ZCSBPANE_ANNO_EMPTY
#endif //#ifndef ACSBPANE_ANNO_EMPTY

#ifndef ACSBPANE_ANNO_STRETCH
#define ACSBPANE_ANNO_STRETCH		ZCSBPANE_ANNO_STRETCH
#endif //#ifndef ACSBPANE_ANNO_STRETCH

#ifndef ACSBPANE_ANNO_VIEWPORT_LOCK_STATE
#define ACSBPANE_ANNO_VIEWPORT_LOCK_STATE		ZCSBPANE_ANNO_VIEWPORT_LOCK_STATE
#endif //#ifndef ACSBPANE_ANNO_VIEWPORT_LOCK_STATE

#ifndef ACSBPANE_ANNO_VIEWPORT_SCALE
#define ACSBPANE_ANNO_VIEWPORT_SCALE		ZCSBPANE_ANNO_VIEWPORT_SCALE
#endif //#ifndef ACSBPANE_ANNO_VIEWPORT_SCALE

#ifndef ACSBPANE_ANNO_VIEWPORT_SCALE_LABEL
#define ACSBPANE_ANNO_VIEWPORT_SCALE_LABEL		ZCSBPANE_ANNO_VIEWPORT_SCALE_LABEL
#endif //#ifndef ACSBPANE_ANNO_VIEWPORT_SCALE_LABEL

#ifndef ACSBPANE_APP_ALL
#define ACSBPANE_APP_ALL		ZCSBPANE_APP_ALL
#endif //#ifndef ACSBPANE_APP_ALL

#ifndef ACSBPANE_APP_CURSORCOORD
#define ACSBPANE_APP_CURSORCOORD		ZCSBPANE_APP_CURSORCOORD
#endif //#ifndef ACSBPANE_APP_CURSORCOORD

#ifndef ACSBPANE_APP_DYNAMICUCS
#define ACSBPANE_APP_DYNAMICUCS		ZCSBPANE_APP_DYNAMICUCS
#endif //#ifndef ACSBPANE_APP_DYNAMICUCS

#ifndef ACSBPANE_APP_DYNINPUT
#define ACSBPANE_APP_DYNINPUT		ZCSBPANE_APP_DYNINPUT
#endif //#ifndef ACSBPANE_APP_DYNINPUT

#ifndef ACSBPANE_APP_FLOAT
#define ACSBPANE_APP_FLOAT		ZCSBPANE_APP_FLOAT
#endif //#ifndef ACSBPANE_APP_FLOAT

#ifndef ACSBPANE_APP_GRID
#define ACSBPANE_APP_GRID		ZCSBPANE_APP_GRID
#endif //#ifndef ACSBPANE_APP_GRID

#ifndef ACSBPANE_APP_LAYOUTMODELICONS
#define ACSBPANE_APP_LAYOUTMODELICONS		ZCSBPANE_APP_LAYOUTMODELICONS
#endif //#ifndef ACSBPANE_APP_LAYOUTMODELICONS

#ifndef ACSBPANE_APP_LAYOUTMORE_ICON
#define ACSBPANE_APP_LAYOUTMORE_ICON		ZCSBPANE_APP_LAYOUTMORE_ICON
#endif //#ifndef ACSBPANE_APP_LAYOUTMORE_ICON

#ifndef ACSBPANE_APP_LAYOUT_ICON
#define ACSBPANE_APP_LAYOUT_ICON		ZCSBPANE_APP_LAYOUT_ICON
#endif //#ifndef ACSBPANE_APP_LAYOUT_ICON

#ifndef ACSBPANE_APP_LINEWEIGHT
#define ACSBPANE_APP_LINEWEIGHT		ZCSBPANE_APP_LINEWEIGHT
#endif //#ifndef ACSBPANE_APP_LINEWEIGHT

#ifndef ACSBPANE_APP_MODEL
#define ACSBPANE_APP_MODEL		ZCSBPANE_APP_MODEL
#endif //#ifndef ACSBPANE_APP_MODEL

#ifndef ACSBPANE_APP_MODEL_ICON
#define ACSBPANE_APP_MODEL_ICON		ZCSBPANE_APP_MODEL_ICON
#endif //#ifndef ACSBPANE_APP_MODEL_ICON

#ifndef ACSBPANE_APP_MODEMACRO
#define ACSBPANE_APP_MODEMACRO		ZCSBPANE_APP_MODEMACRO
#endif //#ifndef ACSBPANE_APP_MODEMACRO

#ifndef ACSBPANE_APP_ORTHO
#define ACSBPANE_APP_ORTHO		ZCSBPANE_APP_ORTHO
#endif //#ifndef ACSBPANE_APP_ORTHO

#ifndef ACSBPANE_APP_OSNAP
#define ACSBPANE_APP_OSNAP		ZCSBPANE_APP_OSNAP
#endif //#ifndef ACSBPANE_APP_OSNAP

#ifndef ACSBPANE_APP_OTRACK
#define ACSBPANE_APP_OTRACK		ZCSBPANE_APP_OTRACK
#endif //#ifndef ACSBPANE_APP_OTRACK

#ifndef ACSBPANE_APP_PAPER
#define ACSBPANE_APP_PAPER		ZCSBPANE_APP_PAPER
#endif //#ifndef ACSBPANE_APP_PAPER

#ifndef ACSBPANE_APP_PAPERMODEL
#define ACSBPANE_APP_PAPERMODEL		ZCSBPANE_APP_PAPERMODEL
#endif //#ifndef ACSBPANE_APP_PAPERMODEL

#ifndef ACSBPANE_APP_POLAR
#define ACSBPANE_APP_POLAR		ZCSBPANE_APP_POLAR
#endif //#ifndef ACSBPANE_APP_POLAR

#ifndef ACSBPANE_APP_SNAP
#define ACSBPANE_APP_SNAP		ZCSBPANE_APP_SNAP
#endif //#ifndef ACSBPANE_APP_SNAP

#ifndef ACSBPANE_APP_SPACER
#define ACSBPANE_APP_SPACER		ZCSBPANE_APP_SPACER
#endif //#ifndef ACSBPANE_APP_SPACER

#ifndef ACSBPANE_APP_TABLET
#define ACSBPANE_APP_TABLET		ZCSBPANE_APP_TABLET
#endif //#ifndef ACSBPANE_APP_TABLET

#ifndef ACSBPANE_APP_VPMAX
#define ACSBPANE_APP_VPMAX		ZCSBPANE_APP_VPMAX
#endif //#ifndef ACSBPANE_APP_VPMAX

#ifndef ACSBPANE_APP_VPMAX_NEXT
#define ACSBPANE_APP_VPMAX_NEXT		ZCSBPANE_APP_VPMAX_NEXT
#endif //#ifndef ACSBPANE_APP_VPMAX_NEXT

#ifndef ACSBPANE_APP_VPMAX_PREV
#define ACSBPANE_APP_VPMAX_PREV		ZCSBPANE_APP_VPMAX_PREV
#endif //#ifndef ACSBPANE_APP_VPMAX_PREV

#ifndef ACSBPANE_APP_STRETCH
#define ACSBPANE_APP_STRETCH ZCSBPANE_APP_STRETCH
#endif //#ifndef ACSBPANE_APP_STRETCH

#ifndef ACSBPANE_APP_WORKSPACE
#define	ACSBPANE_APP_WORKSPACE ZCSBPANE_APP_WORKSPACE
#endif //#ifndef ACSBPANE_APP_WORKSPACE

#ifndef ACSBPANE_APP_WORKSPACE_LOCK
#define	ACSBPANE_APP_WORKSPACE_LOCK ZCSBPANE_APP_WORKSPACE_LOCK
#endif //#ifndef ACSBPANE_APP_WORKSPACE_LOCK

#ifndef ACSBPANE_APP_QPROPERTIES
#define	ACSBPANE_APP_QPROPERTIES ZCSBPANE_APP_QPROPERTIES
#endif //#ifndef ACSBPANE_APP_QPROPERTIES

#ifndef ACSBPANE_ANNO_SYNCHSCALES
#define	ACSBPANE_ANNO_SYNCHSCALES ZCSBPANE_ANNO_SYNCHSCALES
#endif //#ifndef ACSBPANE_ANNO_SYNCHSCALES

#ifndef ACSBPANE_APP_QV_LAYOUTS
#define	ACSBPANE_APP_QV_LAYOUTS ZCSBPANE_APP_QV_LAYOUTS
#endif //#ifndef ACSBPANE_APP_QV_LAYOUTS

#ifndef ACSBPANE_APP_QV_DRAWINGS
#define	ACSBPANE_APP_QV_DRAWINGS ZCSBPANE_APP_QV_DRAWINGS
#endif //#ifndef ACSBPANE_APP_QV_DRAWINGS

#ifndef ACSBPANE_APP_QV_SPACER
#define	ACSBPANE_APP_QV_SPACER ZCSBPANE_APP_QV_SPACER
#endif //#ifndef ACSBPANE_APP_QV_SPACER

#ifndef ACSBPANE_APP_QV_PAN
#define	ACSBPANE_APP_QV_PAN ZCSBPANE_APP_QV_PAN
#endif //#ifndef ACSBPANE_APP_QV_PAN

#ifndef ACSBPANE_APP_QV_ZOOM
#define	ACSBPANE_APP_QV_ZOOM ZCSBPANE_APP_QV_ZOOM
#endif //#ifndef ACSBPANE_APP_QV_ZOOM

#ifndef ACSBPANE_APP_QV_STEERINGWHEEL
#define	ACSBPANE_APP_QV_STEERINGWHEEL ZCSBPANE_APP_QV_STEERINGWHEEL
#endif //#ifndef ACSBPANE_APP_QV_STEERINGWHEEL

#ifndef ACSBPANE_APP_QV_SHOWMOTION
#define	ACSBPANE_APP_QV_SHOWMOTION ZCSBPANE_APP_QV_SHOWMOTION
#endif //#ifndef ACSBPANE_APP_QV_SHOWMOTION

#ifndef ACSBPANE_APP_QV_ANNO_SPACER
#define	ACSBPANE_APP_QV_ANNO_SPACER ZCSBPANE_APP_QV_ANNO_SPACER
#endif //#ifndef ACSBPANE_APP_QV_ANNO_SPACER

#ifndef ACSBPANE_APP_3DOSNAP
#define	ACSBPANE_APP_3DOSNAP ZCSBPANE_APP_3DOSNAP
#endif //#ifndef ACSBPANE_APP_3DOSNAP

#ifndef ACSBPANE_APP_WORKSPACE_PERFORMANCE
#define	ACSBPANE_APP_WORKSPACE_PERFORMANCE ZCSBPANE_APP_WORKSPACE_PERFORMANCE
#endif //#ifndef ACSBPANE_APP_WORKSPACE_PERFORMANCE

#ifndef ACSBPANE_APP_SELECTIONCYCLING
#define	ACSBPANE_APP_SELECTIONCYCLING ZCSBPANE_APP_SELECTIONCYCLING
#endif //#ifndef ACSBPANE_APP_SELECTIONCYCLING

#ifndef ACSBPANE_APP_TRANSPARENCY
#define	ACSBPANE_APP_TRANSPARENCY ZCSBPANE_APP_TRANSPARENCY
#endif //#ifndef ACSBPANE_APP_TRANSPARENCY

#ifndef ACSBPANE_APP_INFER
#define	ACSBPANE_APP_INFER ZCSBPANE_APP_INFER
#endif //#ifndef ACSBPANE_APP_INFER

#ifndef ACSBPANE_APP_ANNOMONITOR
#define	ACSBPANE_APP_ANNOMONITOR ZCSBPANE_APP_ANNOMONITOR
#endif //#ifndef ACSBPANE_APP_ANNOMONITOR

#ifndef ACSB_COMMAND
#define ACSB_COMMAND		ZCSB_COMMAND
#endif //#ifndef ACSB_COMMAND

#ifndef ACSB_NOBORDERS
#define ACSB_NOBORDERS		ZCSB_NOBORDERS
#endif //#ifndef ACSB_NOBORDERS

#ifndef ACSB_NORMAL
#define ACSB_NORMAL		ZCSB_NORMAL
#endif //#ifndef ACSB_NORMAL

#ifndef ACSB_POPOUT
#define ACSB_POPOUT		ZCSB_POPOUT
#endif //#ifndef ACSB_POPOUT

#ifndef ACSB_POPUP
#define ACSB_POPUP		ZCSB_POPUP
#endif //#ifndef ACSB_POPUP

#ifndef ACSB_STRETCH
#define ACSB_STRETCH		ZCSB_STRETCH
#endif //#ifndef ACSB_STRETCH

#ifndef AcApStatusBar
#define AcApStatusBar		ZcApStatusBar
#endif //#ifndef AcApStatusBar

#ifndef AcDefaultPane
#define AcDefaultPane		ZcDefaultPane
#endif //#ifndef AcDefaultPane

#ifndef AcPane
#define AcPane		ZcPane
#endif //#ifndef AcPane

#ifndef AcStatusBarItem
#define AcStatusBarItem		ZcStatusBarItem
#endif //#ifndef AcStatusBarItem

#ifndef AcStatusBarMenuItem
#define AcStatusBarMenuItem		ZcStatusBarMenuItem
#endif //#ifndef AcStatusBarMenuItem

#ifndef AcStatusBarType
#define AcStatusBarType		ZcStatusBarType
#endif //#ifndef AcStatusBarType

#ifndef AcTrayItem
#define AcTrayItem		ZcTrayItem
#endif //#ifndef AcTrayItem

#ifndef AcTrayItemAnimationCallbackData
#define AcTrayItemAnimationCallbackData		ZcTrayItemAnimationCallbackData
#endif //#ifndef AcTrayItemAnimationCallbackData

#ifndef AcTrayItemAnimationCallbackFunc
#define AcTrayItemAnimationCallbackFunc		ZcTrayItemAnimationCallbackFunc
#endif //#ifndef AcTrayItemAnimationCallbackFunc

#ifndef AcTrayItemAnimationControl
#define AcTrayItemAnimationControl		ZcTrayItemAnimationControl
#endif //#ifndef AcTrayItemAnimationControl

#ifndef AcTrayItemBubbleWindowCallbackData
#define AcTrayItemBubbleWindowCallbackData		ZcTrayItemBubbleWindowCallbackData
#endif //#ifndef AcTrayItemBubbleWindowCallbackData

#ifndef AcTrayItemBubbleWindowCallbackFunc
#define AcTrayItemBubbleWindowCallbackFunc		ZcTrayItemBubbleWindowCallbackFunc
#endif //#ifndef AcTrayItemBubbleWindowCallbackFunc

#ifndef AcTrayItemBubbleWindowControl
#define AcTrayItemBubbleWindowControl		ZcTrayItemBubbleWindowControl
#endif //#ifndef AcTrayItemBubbleWindowControl

#endif //#ifndef __ACSTATUSBAR_H__
