
#ifndef __ACTCUICATALOGVIEWITEM_H__
#define __ACTCUICATALOGVIEWITEM_H__

#include "AcTc.h"
#include "AcTcUi.h"

#include "../inc/zAcTcUiCatalogViewItem.h"

#ifndef ACTCUI_CVIR_BOUNDS
#define ACTCUI_CVIR_BOUNDS		ZCTCUI_CVIR_BOUNDS
#endif //#ifndef ACTCUI_CVIR_BOUNDS

#ifndef ACTCUI_CVIR_IMAGE
#define ACTCUI_CVIR_IMAGE		ZCTCUI_CVIR_IMAGE
#endif //#ifndef ACTCUI_CVIR_IMAGE

#ifndef ACTCUI_CVIR_LABEL
#define ACTCUI_CVIR_LABEL		ZCTCUI_CVIR_LABEL
#endif //#ifndef ACTCUI_CVIR_LABEL

#ifndef ACTCUI_CVIR_TRIGGER
#define ACTCUI_CVIR_TRIGGER		ZCTCUI_CVIR_TRIGGER
#endif //#ifndef ACTCUI_CVIR_TRIGGER

#ifndef ACTCUI_CVIR_USEFULLLABEL
#define ACTCUI_CVIR_USEFULLLABEL		ZCTCUI_CVIR_USEFULLLABEL
#endif //#ifndef ACTCUI_CVIR_USEFULLLABEL

#ifndef ACTCUI_CVIR_WORLDRECT
#define ACTCUI_CVIR_WORLDRECT		ZCTCUI_CVIR_WORLDRECT
#endif //#ifndef ACTCUI_CVIR_WORLDRECT

#ifndef ACTCUI_CVISTATE_FOCUSED
#define ACTCUI_CVISTATE_FOCUSED		ZCTCUI_CVISTATE_FOCUSED
#endif //#ifndef ACTCUI_CVISTATE_FOCUSED

#ifndef ACTCUI_CVISTATE_HALO
#define ACTCUI_CVISTATE_HALO		ZCTCUI_CVISTATE_HALO
#endif //#ifndef ACTCUI_CVISTATE_HALO

#ifndef ACTCUI_CVISTATE_HIGHLIGHTED
#define ACTCUI_CVISTATE_HIGHLIGHTED		ZCTCUI_CVISTATE_HIGHLIGHTED
#endif //#ifndef ACTCUI_CVISTATE_HIGHLIGHTED

#ifndef ACTCUI_CVISTATE_SELECTED
#define ACTCUI_CVISTATE_SELECTED		ZCTCUI_CVISTATE_SELECTED
#endif //#ifndef ACTCUI_CVISTATE_SELECTED

#ifndef ACTCUI_CVISTYLE_FLYOUT
#define ACTCUI_CVISTYLE_FLYOUT		ZCTCUI_CVISTYLE_FLYOUT
#endif //#ifndef ACTCUI_CVISTYLE_FLYOUT

#ifndef ACTCUI_CVISTYLE_FULLROW
#define ACTCUI_CVISTYLE_FULLROW		ZCTCUI_CVISTYLE_FULLROW
#endif //#ifndef ACTCUI_CVISTYLE_FULLROW

#ifndef ACTCUI_CVISTYLE_HIDEIMAGE
#define ACTCUI_CVISTYLE_HIDEIMAGE		ZCTCUI_CVISTYLE_HIDEIMAGE
#endif //#ifndef ACTCUI_CVISTYLE_HIDEIMAGE

#ifndef ACTCUI_CVISTYLE_PUSHBUTTON
#define ACTCUI_CVISTYLE_PUSHBUTTON		ZCTCUI_CVISTYLE_PUSHBUTTON
#endif //#ifndef ACTCUI_CVISTYLE_PUSHBUTTON

#ifndef ACTCUI_CVISTYLE_RIGHTTEXT
#define ACTCUI_CVISTYLE_RIGHTTEXT		ZCTCUI_CVISTYLE_RIGHTTEXT
#endif //#ifndef ACTCUI_CVISTYLE_RIGHTTEXT

#ifndef ACTCUI_CVISTYLE_SEPARATOR
#define ACTCUI_CVISTYLE_SEPARATOR		ZCTCUI_CVISTYLE_SEPARATOR
#endif //#ifndef ACTCUI_CVISTYLE_SEPARATOR

#ifndef ACTCUI_CVISTYLE_SHOWTEXT
#define ACTCUI_CVISTYLE_SHOWTEXT		ZCTCUI_CVISTYLE_SHOWTEXT
#endif //#ifndef ACTCUI_CVISTYLE_SHOWTEXT

#ifndef ACTCUI_CVISTYLE_TEXT
#define ACTCUI_CVISTYLE_TEXT		ZCTCUI_CVISTYLE_TEXT
#endif //#ifndef ACTCUI_CVISTYLE_TEXT

#ifndef ACTCUI_PORT
#define ACTCUI_PORT		ZCTCUI_PORT
#endif //#ifndef ACTCUI_PORT

#ifndef AcTc
#define AcTc		ZcTc
#endif //#ifndef AcTc

#ifndef AcTcCatalogItem
#define AcTcCatalogItem		ZcTcCatalogItem
#endif //#ifndef AcTcCatalogItem

#ifndef AcTcUi
#define AcTcUi		ZcTcUi
#endif //#ifndef AcTcUi

#ifndef AcTcUiSystemInternals
#define AcTcUiSystemInternals		ZcTcUiSystemInternals
#endif //#ifndef AcTcUiSystemInternals

#ifndef CAcTcUiCatalogView
#define CAcTcUiCatalogView		CZcTcUiCatalogView
#endif //#ifndef CAcTcUiCatalogView

#ifndef CAcTcUiCatalogViewItem
#define CAcTcUiCatalogViewItem		CZcTcUiCatalogViewItem
#endif //#ifndef CAcTcUiCatalogViewItem

#ifndef CAcTcUiCatalogViewItemArray
#define CAcTcUiCatalogViewItemArray		CZcTcUiCatalogViewItemArray
#endif //#ifndef CAcTcUiCatalogViewItemArray

#ifndef CAcTcUiImpCatalogView
#define CAcTcUiImpCatalogView		CZcTcUiImpCatalogView
#endif //#ifndef CAcTcUiImpCatalogView

#endif //#ifndef __ACTCUICATALOGVIEWITEM_H__
