
#ifndef __ACTCUICATALOGVIEW_H__
#define __ACTCUICATALOGVIEW_H__

#include "AcTcUi.h"
#include "AcTcUiCatalogViewItem.h"

#include "../inc/zAcTcUiCatalogView.h"

#ifndef ACTCUI_CVHT_ABOVE
#define ACTCUI_CVHT_ABOVE		ZCTCUI_CVHT_ABOVE
#endif //#ifndef ACTCUI_CVHT_ABOVE

#ifndef ACTCUI_CVHT_BACKGROUND
#define ACTCUI_CVHT_BACKGROUND		ZCTCUI_CVHT_BACKGROUND
#endif //#ifndef ACTCUI_CVHT_BACKGROUND

#ifndef ACTCUI_CVHT_BELOW
#define ACTCUI_CVHT_BELOW		ZCTCUI_CVHT_BELOW
#endif //#ifndef ACTCUI_CVHT_BELOW

#ifndef ACTCUI_CVHT_ITEM
#define ACTCUI_CVHT_ITEM		ZCTCUI_CVHT_ITEM
#endif //#ifndef ACTCUI_CVHT_ITEM

#ifndef ACTCUI_CVHT_ITEMIMAGE
#define ACTCUI_CVHT_ITEMIMAGE		ZCTCUI_CVHT_ITEMIMAGE
#endif //#ifndef ACTCUI_CVHT_ITEMIMAGE

#ifndef ACTCUI_CVHT_ITEMLABEL
#define ACTCUI_CVHT_ITEMLABEL		ZCTCUI_CVHT_ITEMLABEL
#endif //#ifndef ACTCUI_CVHT_ITEMLABEL

#ifndef ACTCUI_CVHT_ITEMTRIGGER
#define ACTCUI_CVHT_ITEMTRIGGER		ZCTCUI_CVHT_ITEMTRIGGER
#endif //#ifndef ACTCUI_CVHT_ITEMTRIGGER

#ifndef ACTCUI_CVHT_LEFT
#define ACTCUI_CVHT_LEFT		ZCTCUI_CVHT_LEFT
#endif //#ifndef ACTCUI_CVHT_LEFT

#ifndef ACTCUI_CVHT_NOWHERE
#define ACTCUI_CVHT_NOWHERE		ZCTCUI_CVHT_NOWHERE
#endif //#ifndef ACTCUI_CVHT_NOWHERE

#ifndef ACTCUI_CVHT_RIGHT
#define ACTCUI_CVHT_RIGHT		ZCTCUI_CVHT_RIGHT
#endif //#ifndef ACTCUI_CVHT_RIGHT

#ifndef ACTCUI_CVISTYLE_SHOWTEXT
#define ACTCUI_CVISTYLE_SHOWTEXT		ZCTCUI_CVISTYLE_SHOWTEXT
#endif //#ifndef ACTCUI_CVISTYLE_SHOWTEXT

#ifndef ACTCUI_CVSTYLE_EDITLABELS
#define ACTCUI_CVSTYLE_EDITLABELS		ZCTCUI_CVSTYLE_EDITLABELS
#endif //#ifndef ACTCUI_CVSTYLE_EDITLABELS

#ifndef ACTCUI_CVSTYLE_HOVERSELECT
#define ACTCUI_CVSTYLE_HOVERSELECT		ZCTCUI_CVSTYLE_HOVERSELECT
#endif //#ifndef ACTCUI_CVSTYLE_HOVERSELECT

#ifndef ACTCUI_CVSTYLE_LISTVIEW
#define ACTCUI_CVSTYLE_LISTVIEW		ZCTCUI_CVSTYLE_LISTVIEW
#endif //#ifndef ACTCUI_CVSTYLE_LISTVIEW

#ifndef ACTCUI_CVSTYLE_MULTISELECT
#define ACTCUI_CVSTYLE_MULTISELECT		ZCTCUI_CVSTYLE_MULTISELECT
#endif //#ifndef ACTCUI_CVSTYLE_MULTISELECT

#ifndef ACTCUI_CVSTYLE_NO_COPY
#define ACTCUI_CVSTYLE_NO_COPY		ZCTCUI_CVSTYLE_NO_COPY
#endif //#ifndef ACTCUI_CVSTYLE_NO_COPY

#ifndef ACTCUI_CVSTYLE_NO_CUT
#define ACTCUI_CVSTYLE_NO_CUT		ZCTCUI_CVSTYLE_NO_CUT
#endif //#ifndef ACTCUI_CVSTYLE_NO_CUT

#ifndef ACTCUI_CVSTYLE_NO_DRAGDROP
#define ACTCUI_CVSTYLE_NO_DRAGDROP		ZCTCUI_CVSTYLE_NO_DRAGDROP
#endif //#ifndef ACTCUI_CVSTYLE_NO_DRAGDROP

#ifndef ACTCUI_CVSTYLE_NO_FLYOUT
#define ACTCUI_CVSTYLE_NO_FLYOUT		ZCTCUI_CVSTYLE_NO_FLYOUT
#endif //#ifndef ACTCUI_CVSTYLE_NO_FLYOUT

#ifndef ACTCUI_CVSTYLE_NO_HELP
#define ACTCUI_CVSTYLE_NO_HELP		ZCTCUI_CVSTYLE_NO_HELP
#endif //#ifndef ACTCUI_CVSTYLE_NO_HELP

#ifndef ACTCUI_CVSTYLE_NO_OPERATIONS
#define ACTCUI_CVSTYLE_NO_OPERATIONS		ZCTCUI_CVSTYLE_NO_OPERATIONS
#endif //#ifndef ACTCUI_CVSTYLE_NO_OPERATIONS

#ifndef ACTCUI_CVSTYLE_NO_PASTE
#define ACTCUI_CVSTYLE_NO_PASTE		ZCTCUI_CVSTYLE_NO_PASTE
#endif //#ifndef ACTCUI_CVSTYLE_NO_PASTE

#ifndef ACTCUI_CVSTYLE_NO_PROPERTIES
#define ACTCUI_CVSTYLE_NO_PROPERTIES		ZCTCUI_CVSTYLE_NO_PROPERTIES
#endif //#ifndef ACTCUI_CVSTYLE_NO_PROPERTIES

#ifndef ACTCUI_CVSTYLE_NO_QSL
#define ACTCUI_CVSTYLE_NO_QSL		ZCTCUI_CVSTYLE_NO_QSL
#endif //#ifndef ACTCUI_CVSTYLE_NO_QSL

#ifndef ACTCUI_CVSTYLE_NO_REFRESH
#define ACTCUI_CVSTYLE_NO_REFRESH		ZCTCUI_CVSTYLE_NO_REFRESH
#endif //#ifndef ACTCUI_CVSTYLE_NO_REFRESH

#ifndef ACTCUI_CVSTYLE_NO_REMOVE
#define ACTCUI_CVSTYLE_NO_REMOVE		ZCTCUI_CVSTYLE_NO_REMOVE
#endif //#ifndef ACTCUI_CVSTYLE_NO_REMOVE

#ifndef ACTCUI_CVSTYLE_NO_RENAME
#define ACTCUI_CVSTYLE_NO_RENAME		ZCTCUI_CVSTYLE_NO_RENAME
#endif //#ifndef ACTCUI_CVSTYLE_NO_RENAME

#ifndef ACTCUI_CVSTYLE_NO_SCROLLBAR
#define ACTCUI_CVSTYLE_NO_SCROLLBAR		ZCTCUI_CVSTYLE_NO_SCROLLBAR
#endif //#ifndef ACTCUI_CVSTYLE_NO_SCROLLBAR

#ifndef ACTCUI_CVSTYLE_NO_SELECTION
#define ACTCUI_CVSTYLE_NO_SELECTION		ZCTCUI_CVSTYLE_NO_SELECTION
#endif //#ifndef ACTCUI_CVSTYLE_NO_SELECTION

#ifndef ACTCUI_CVSTYLE_NO_VIEWOPTIONS
#define ACTCUI_CVSTYLE_NO_VIEWOPTIONS		ZCTCUI_CVSTYLE_NO_VIEWOPTIONS
#endif //#ifndef ACTCUI_CVSTYLE_NO_VIEWOPTIONS

#ifndef ACTCUI_CVSTYLE_NO_VIEW_BUTTON
#define ACTCUI_CVSTYLE_NO_VIEW_BUTTON		ZCTCUI_CVSTYLE_NO_VIEW_BUTTON
#endif //#ifndef ACTCUI_CVSTYLE_NO_VIEW_BUTTON

#ifndef ACTCUI_CVSTYLE_SAVE_ORDER_IN_CATALOG
#define ACTCUI_CVSTYLE_SAVE_ORDER_IN_CATALOG		ZCTCUI_CVSTYLE_SAVE_ORDER_IN_CATALOG
#endif //#ifndef ACTCUI_CVSTYLE_SAVE_ORDER_IN_CATALOG

#ifndef ACTCUI_CVSTYLE_SHOWTEXT
#define ACTCUI_CVSTYLE_SHOWTEXT		ZCTCUI_CVSTYLE_SHOWTEXT
#endif //#ifndef ACTCUI_CVSTYLE_SHOWTEXT

#ifndef ACTCUI_CVSTYLE_TOOLTIPS
#define ACTCUI_CVSTYLE_TOOLTIPS		ZCTCUI_CVSTYLE_TOOLTIPS
#endif //#ifndef ACTCUI_CVSTYLE_TOOLTIPS

#ifndef ACTCUI_DDO_ACCEPT_ALL_ITEMS
#define ACTCUI_DDO_ACCEPT_ALL_ITEMS		ZCTCUI_DDO_ACCEPT_ALL_ITEMS
#endif //#ifndef ACTCUI_DDO_ACCEPT_ALL_ITEMS

#ifndef ACTCUI_DDO_ACCEPT_CATALOG
#define ACTCUI_DDO_ACCEPT_CATALOG		ZCTCUI_DDO_ACCEPT_CATALOG
#endif //#ifndef ACTCUI_DDO_ACCEPT_CATALOG

#ifndef ACTCUI_DDO_ACCEPT_CATEGORY
#define ACTCUI_DDO_ACCEPT_CATEGORY		ZCTCUI_DDO_ACCEPT_CATEGORY
#endif //#ifndef ACTCUI_DDO_ACCEPT_CATEGORY

#ifndef ACTCUI_DDO_ACCEPT_FILES
#define ACTCUI_DDO_ACCEPT_FILES		ZCTCUI_DDO_ACCEPT_FILES
#endif //#ifndef ACTCUI_DDO_ACCEPT_FILES

#ifndef ACTCUI_DDO_ACCEPT_PACKAGE
#define ACTCUI_DDO_ACCEPT_PACKAGE		ZCTCUI_DDO_ACCEPT_PACKAGE
#endif //#ifndef ACTCUI_DDO_ACCEPT_PACKAGE

#ifndef ACTCUI_DDO_ACCEPT_PALETTE
#define ACTCUI_DDO_ACCEPT_PALETTE		ZCTCUI_DDO_ACCEPT_PALETTE
#endif //#ifndef ACTCUI_DDO_ACCEPT_PALETTE

#ifndef ACTCUI_DDO_ACCEPT_STOCKTOOL
#define ACTCUI_DDO_ACCEPT_STOCKTOOL		ZCTCUI_DDO_ACCEPT_STOCKTOOL
#endif //#ifndef ACTCUI_DDO_ACCEPT_STOCKTOOL

#ifndef ACTCUI_DDO_ACCEPT_TOOL
#define ACTCUI_DDO_ACCEPT_TOOL		ZCTCUI_DDO_ACCEPT_TOOL
#endif //#ifndef ACTCUI_DDO_ACCEPT_TOOL

#ifndef ACTCUI_IDW_CATALOGVIEW
#define ACTCUI_IDW_CATALOGVIEW		ZCTCUI_IDW_CATALOGVIEW
#endif //#ifndef ACTCUI_IDW_CATALOGVIEW

#ifndef ACTCUI_OVERLAY_ALIGN_BOTTOMLEFT
#define ACTCUI_OVERLAY_ALIGN_BOTTOMLEFT		ZCTCUI_OVERLAY_ALIGN_BOTTOMLEFT
#endif //#ifndef ACTCUI_OVERLAY_ALIGN_BOTTOMLEFT

#ifndef ACTCUI_OVERLAY_ALIGN_BOTTOMRIGHT
#define ACTCUI_OVERLAY_ALIGN_BOTTOMRIGHT		ZCTCUI_OVERLAY_ALIGN_BOTTOMRIGHT
#endif //#ifndef ACTCUI_OVERLAY_ALIGN_BOTTOMRIGHT

#ifndef ACTCUI_OVERLAY_ALIGN_TOPLEFT
#define ACTCUI_OVERLAY_ALIGN_TOPLEFT		ZCTCUI_OVERLAY_ALIGN_TOPLEFT
#endif //#ifndef ACTCUI_OVERLAY_ALIGN_TOPLEFT

#ifndef ACTCUI_OVERLAY_ALIGN_TOPRIGHT
#define ACTCUI_OVERLAY_ALIGN_TOPRIGHT		ZCTCUI_OVERLAY_ALIGN_TOPRIGHT
#endif //#ifndef ACTCUI_OVERLAY_ALIGN_TOPRIGHT

#ifndef ACTCUI_PORT
#define ACTCUI_PORT		ZCTCUI_PORT
#endif //#ifndef ACTCUI_PORT

#ifndef ADUI_DRAGDATA
#define ADUI_DRAGDATA		ZDUI_DRAGDATA
#endif //#ifndef ADUI_DRAGDATA

#ifndef AcTcCatalogItem
#define AcTcCatalogItem		ZcTcCatalogItem
#endif //#ifndef AcTcCatalogItem

#ifndef AcTcCatalogItemArray
#define AcTcCatalogItemArray		ZcTcCatalogItemArray
#endif //#ifndef AcTcCatalogItemArray

#ifndef AcTcUi
#define AcTcUi		ZcTcUi
#endif //#ifndef AcTcUi

#ifndef AcTcUiCatalogViewItem
#define AcTcUiCatalogViewItem		ZcTcUiCatalogViewItem
#endif //#ifndef AcTcUiCatalogViewItem

#ifndef AcTcUiSystemInternals
#define AcTcUiSystemInternals		ZcTcUiSystemInternals
#endif //#ifndef AcTcUiSystemInternals

#ifndef CAcTcUiCatalogView
#define CAcTcUiCatalogView		CZcTcUiCatalogView
#endif //#ifndef CAcTcUiCatalogView

#ifndef CAcTcUiCatalogViewItem
#define CAcTcUiCatalogViewItem		CZcTcUiCatalogViewItem
#endif //#ifndef CAcTcUiCatalogViewItem

#ifndef CAcTcUiCatalogViewItemArray
#define CAcTcUiCatalogViewItemArray		CZcTcUiCatalogViewItemArray
#endif //#ifndef CAcTcUiCatalogViewItemArray

#ifndef CAcTcUiImpCatalogView
#define CAcTcUiImpCatalogView		CZcTcUiImpCatalogView
#endif //#ifndef CAcTcUiImpCatalogView

#ifndef CAcTcUiScheme
#define CAcTcUiScheme		CZcTcUiScheme
#endif //#ifndef CAcTcUiScheme

#ifndef OnBeginAcadDrop
#define OnBeginAcadDrop		OnBeginZcadDrop
#endif //#ifndef OnBeginAcadDrop

#ifndef OnEndAcadDrop
#define OnEndAcadDrop		OnEndZcadDrop
#endif //#ifndef OnEndAcadDrop

#endif //#ifndef __ACTCUICATALOGVIEW_H__
