
#ifndef __ADUIGROUPCTRL_H__
#define __ADUIGROUPCTRL_H__

#include <vector>

#include "../inc/zaduiGroupCtrl.h"

#ifndef ADUIGROUPCTRLDATALIST
#define ADUIGROUPCTRLDATALIST		ZDUIGROUPCTRLDATALIST
#endif //#ifndef ADUIGROUPCTRLDATALIST

#ifndef ADUIHEADERBTNLIST
#define ADUIHEADERBTNLIST		ZDUIHEADERBTNLIST
#endif //#ifndef ADUIHEADERBTNLIST

#ifndef ADUI_GROUP_BORDER_SIZE
#define ADUI_GROUP_BORDER_SIZE		ZDUI_GROUP_BORDER_SIZE
#endif //#ifndef ADUI_GROUP_BORDER_SIZE

#ifndef ADUI_GROUP_BUTTONS_RIGHT
#define ADUI_GROUP_BUTTONS_RIGHT		ZDUI_GROUP_BUTTONS_RIGHT
#endif //#ifndef ADUI_GROUP_BUTTONS_RIGHT

#ifndef ADUI_GROUP_BUTTON_BOTTOMPADDING
#define ADUI_GROUP_BUTTON_BOTTOMPADDING		ZDUI_GROUP_BUTTON_BOTTOMPADDING
#endif //#ifndef ADUI_GROUP_BUTTON_BOTTOMPADDING

#ifndef ADUI_GROUP_BUTTON_SIZE
#define ADUI_GROUP_BUTTON_SIZE		ZDUI_GROUP_BUTTON_SIZE
#endif //#ifndef ADUI_GROUP_BUTTON_SIZE

#ifndef ADUI_GROUP_BUTTON_SPACE
#define ADUI_GROUP_BUTTON_SPACE		ZDUI_GROUP_BUTTON_SPACE
#endif //#ifndef ADUI_GROUP_BUTTON_SPACE

#ifndef ADUI_GROUP_BUTTON_TOPPADDING
#define ADUI_GROUP_BUTTON_TOPPADDING		ZDUI_GROUP_BUTTON_TOPPADDING
#endif //#ifndef ADUI_GROUP_BUTTON_TOPPADDING

#ifndef ADUI_GROUP_CHEVRON_RIGHT
#define ADUI_GROUP_CHEVRON_RIGHT		ZDUI_GROUP_CHEVRON_RIGHT
#endif //#ifndef ADUI_GROUP_CHEVRON_RIGHT

#ifndef ADUI_GROUP_CHILD_VERT_SPACE
#define ADUI_GROUP_CHILD_VERT_SPACE		ZDUI_GROUP_CHILD_VERT_SPACE
#endif //#ifndef ADUI_GROUP_CHILD_VERT_SPACE

#ifndef ADUI_GROUP_STYLE_CHEVRON
#define ADUI_GROUP_STYLE_CHEVRON		ZDUI_GROUP_STYLE_CHEVRON
#endif //#ifndef ADUI_GROUP_STYLE_CHEVRON

#ifndef ADUI_GROUP_STYLE_NONACTIVE
#define ADUI_GROUP_STYLE_NONACTIVE		ZDUI_GROUP_STYLE_NONACTIVE
#endif //#ifndef ADUI_GROUP_STYLE_NONACTIVE

#ifndef ADUI_GROUP_STYLE_OPAQUEIMAGE
#define ADUI_GROUP_STYLE_OPAQUEIMAGE	ZDUI_GROUP_STYLE_OPAQUEIMAGE
#endif //#ifndef ADUI_GROUP_STYLE_OPAQUEIMAGE

#ifndef ADUI_GROUP_STYLE_SHOWBTNFORCE
#define ADUI_GROUP_STYLE_SHOWBTNFORCE		ZDUI_GROUP_STYLE_SHOWBTNFORCE
#endif //#ifndef ADUI_GROUP_STYLE_SHOWBTNFORCE

#ifndef ADUI_GROUP_TITLE_BEVELSIZE
#define ADUI_GROUP_TITLE_BEVELSIZE		ZDUI_GROUP_TITLE_BEVELSIZE
#endif //#ifndef ADUI_GROUP_TITLE_BEVELSIZE

#ifndef ADUI_GROUP_TITLE_HEIGHT
#define ADUI_GROUP_TITLE_HEIGHT		ZDUI_GROUP_TITLE_HEIGHT
#endif //#ifndef ADUI_GROUP_TITLE_HEIGHT

#ifndef ADUI_GROUP_TITLE_TEXTLEFT
#define ADUI_GROUP_TITLE_TEXTLEFT		ZDUI_GROUP_TITLE_TEXTLEFT
#endif //#ifndef ADUI_GROUP_TITLE_TEXTLEFT

#ifndef ADUI_GROUP_TITLE_TEXTTOP
#define ADUI_GROUP_TITLE_TEXTTOP		ZDUI_GROUP_TITLE_TEXTTOP
#endif //#ifndef ADUI_GROUP_TITLE_TEXTTOP

#ifndef ADUI_GROUP_TITLE_TEXTBOTTOM
#define ADUI_GROUP_TITLE_TEXTBOTTOM		ZDUI_GROUP_TITLE_TEXTBOTTOM
#endif 

#ifndef ADUI_GROUP_CHEVRON_TOPPADDING
#define ADUI_GROUP_CHEVRON_TOPPADDING	ZDUI_GROUP_CHEVRON_TOPPADDING
#endif 

#ifndef ADUI_GROUP_CHEVRON_BOTTOMPADDING
#define ADUI_GROUP_CHEVRON_BOTTOMPADDING	ZDUI_GROUP_CHEVRON_BOTTOMPADDING
#endif 

#ifndef ADUI_GROUP_EXPANDER_RIGHT_OFFSET
#define ADUI_GROUP_EXPANDER_RIGHT_OFFSET	ZDUI_GROUP_EXPANDER_RIGHT_OFFSET
#endif //#ifndef ADUI_GROUP_EXPANDER_RIGHT_OFFSET

#ifndef ADUI_NCHT_BASE
#define ADUI_NCHT_BASE		ZDUI_NCHT_BASE
#endif //#ifndef ADUI_NCHT_BASE

#ifndef ADUI_NCHT_BUTTON
#define ADUI_NCHT_BUTTON		ZDUI_NCHT_BUTTON
#endif //#ifndef ADUI_NCHT_BUTTON

#ifndef ADUI_NCHT_CHEVRON
#define ADUI_NCHT_CHEVRON		ZDUI_NCHT_CHEVRON
#endif //#ifndef ADUI_NCHT_CHEVRON

#ifndef ADUI_NCHT_TITLE
#define ADUI_NCHT_TITLE		ZDUI_NCHT_TITLE
#endif //#ifndef ADUI_NCHT_TITLE

#ifndef ADUI_PORT
#define ADUI_PORT		ZDUI_PORT
#endif //#ifndef ADUI_PORT

#ifndef CAdUiGroupCtrl
#define CAdUiGroupCtrl		CZdUiGroupCtrl
#endif //#ifndef CAdUiGroupCtrl

#ifndef CAdUiTheme
#define CAdUiTheme		CZdUiTheme
#endif //#ifndef CAdUiTheme

#ifndef WM_ADUI_VISIBILITY_CHANGING
#define WM_ADUI_VISIBILITY_CHANGING		WM_ZDUI_VISIBILITY_CHANGING
#endif //#ifndef WM_ADUI_VISIBILITY_CHANGING

#ifndef AdUiBmpBtnFcnPtr
#define AdUiBmpBtnFcnPtr		ZdUiBmpBtnFcnPtr
#endif //#ifndef AdUiBmpBtnFcnPtr

#ifndef AdUiGroupCtrlData
#define AdUiGroupCtrlData		ZdUiGroupCtrlData
#endif //#ifndef AdUiGroupCtrlData

#ifndef AdUiBmpBtnData
#define AdUiBmpBtnData		ZdUiBmpBtnData
#endif //#ifndef AdUiBmpBtnData

#endif //#ifndef __ADUIGROUPCTRL_H__