
#ifndef __DCDISPID_H__
#define __DCDISPID_H__

#include "../inc/zdcdispid.h"

#ifndef ACDC_MAKE_DISPID
#define ACDC_MAKE_DISPID		ZCDC_MAKE_DISPID
#endif //#ifndef ACDC_MAKE_DISPID

#ifndef DISPID_IAcDcContentBrowser_AddNavigatorNode
#define DISPID_IAcDcContentBrowser_AddNavigatorNode		DISPID_IZcDcContentBrowser_AddNavigatorNode
#endif //#ifndef DISPID_IAcDcContentBrowser_AddNavigatorNode

#ifndef DISPID_IAcDcContentBrowser_AddPaletteItem
#define DISPID_IAcDcContentBrowser_AddPaletteItem		DISPID_IZcDcContentBrowser_AddPaletteItem
#endif //#ifndef DISPID_IAcDcContentBrowser_AddPaletteItem

#ifndef DISPID_IAcDcContentBrowser_DeleteAllPaletteItems
#define DISPID_IAcDcContentBrowser_DeleteAllPaletteItems		DISPID_IZcDcContentBrowser_DeleteAllPaletteItems
#endif //#ifndef DISPID_IAcDcContentBrowser_DeleteAllPaletteItems

#ifndef DISPID_IAcDcContentBrowser_GetCurrentViewMode
#define DISPID_IAcDcContentBrowser_GetCurrentViewMode		DISPID_IZcDcContentBrowser_GetCurrentViewMode
#endif //#ifndef DISPID_IAcDcContentBrowser_GetCurrentViewMode

#ifndef DISPID_IAcDcContentBrowser_GetDCFrameWindow
#define DISPID_IAcDcContentBrowser_GetDCFrameWindow		DISPID_IZcDcContentBrowser_GetDCFrameWindow
#endif //#ifndef DISPID_IAcDcContentBrowser_GetDCFrameWindow

#ifndef DISPID_IAcDcContentBrowser_GetDCStatusBar
#define DISPID_IAcDcContentBrowser_GetDCStatusBar		DISPID_IZcDcContentBrowser_GetDCStatusBar
#endif //#ifndef DISPID_IAcDcContentBrowser_GetDCStatusBar

#ifndef DISPID_IAcDcContentBrowser_GetPaneInfo
#define DISPID_IAcDcContentBrowser_GetPaneInfo		DISPID_IZcDcContentBrowser_GetPaneInfo
#endif //#ifndef DISPID_IAcDcContentBrowser_GetPaneInfo

#ifndef DISPID_IAcDcContentBrowser_GetSelectedNavNodeText
#define DISPID_IAcDcContentBrowser_GetSelectedNavNodeText		DISPID_IZcDcContentBrowser_GetSelectedNavNodeText
#endif //#ifndef DISPID_IAcDcContentBrowser_GetSelectedNavNodeText

#ifndef DISPID_IAcDcContentBrowser_InsertPaletteColumn
#define DISPID_IAcDcContentBrowser_InsertPaletteColumn		DISPID_IZcDcContentBrowser_InsertPaletteColumn
#endif //#ifndef DISPID_IAcDcContentBrowser_InsertPaletteColumn

#ifndef DISPID_IAcDcContentBrowser_NavigateTo
#define DISPID_IAcDcContentBrowser_NavigateTo		DISPID_IZcDcContentBrowser_NavigateTo
#endif //#ifndef DISPID_IAcDcContentBrowser_NavigateTo

#ifndef DISPID_IAcDcContentBrowser_RestorePaletteSelection
#define DISPID_IAcDcContentBrowser_RestorePaletteSelection		DISPID_IZcDcContentBrowser_RestorePaletteSelection
#endif //#ifndef DISPID_IAcDcContentBrowser_RestorePaletteSelection

#ifndef DISPID_IAcDcContentBrowser_SetItemDescription
#define DISPID_IAcDcContentBrowser_SetItemDescription		DISPID_IZcDcContentBrowser_SetItemDescription
#endif //#ifndef DISPID_IAcDcContentBrowser_SetItemDescription

#ifndef DISPID_IAcDcContentBrowser_SetNavigatorImageList
#define DISPID_IAcDcContentBrowser_SetNavigatorImageList		DISPID_IZcDcContentBrowser_SetNavigatorImageList
#endif //#ifndef DISPID_IAcDcContentBrowser_SetNavigatorImageList

#ifndef DISPID_IAcDcContentBrowser_SetPaletteImageList
#define DISPID_IAcDcContentBrowser_SetPaletteImageList		DISPID_IZcDcContentBrowser_SetPaletteImageList
#endif //#ifndef DISPID_IAcDcContentBrowser_SetPaletteImageList

#ifndef DISPID_IAcDcContentBrowser_SetPaletteMultiSelect
#define DISPID_IAcDcContentBrowser_SetPaletteMultiSelect		DISPID_IZcDcContentBrowser_SetPaletteMultiSelect
#endif //#ifndef DISPID_IAcDcContentBrowser_SetPaletteMultiSelect

#ifndef DISPID_IAcDcContentBrowser_SetPaletteSubItem
#define DISPID_IAcDcContentBrowser_SetPaletteSubItem		DISPID_IZcDcContentBrowser_SetPaletteSubItem
#endif //#ifndef DISPID_IAcDcContentBrowser_SetPaletteSubItem

#ifndef DISPID_IAcDcContentBrowser_SetPaletteViewType
#define DISPID_IAcDcContentBrowser_SetPaletteViewType		DISPID_IZcDcContentBrowser_SetPaletteViewType
#endif //#ifndef DISPID_IAcDcContentBrowser_SetPaletteViewType

#ifndef DISPID_IAcDcContentBrowser_SortPaletteItems
#define DISPID_IAcDcContentBrowser_SortPaletteItems		DISPID_IZcDcContentBrowser_SortPaletteItems
#endif //#ifndef DISPID_IAcDcContentBrowser_SortPaletteItems

#ifndef DISPID_IAcDcContentView_DeleteItemData
#define DISPID_IAcDcContentView_DeleteItemData		DISPID_IZcDcContentView_DeleteItemData
#endif //#ifndef DISPID_IAcDcContentView_DeleteItemData

#ifndef DISPID_IAcDcContentView_GetCommandString
#define DISPID_IAcDcContentView_GetCommandString		DISPID_IZcDcContentView_GetCommandString
#endif //#ifndef DISPID_IAcDcContentView_GetCommandString

#ifndef DISPID_IAcDcContentView_GetLargeIcon
#define DISPID_IAcDcContentView_GetLargeIcon		DISPID_IZcDcContentView_GetLargeIcon
#endif //#ifndef DISPID_IAcDcContentView_GetLargeIcon

#ifndef DISPID_IAcDcContentView_GetLargeImageListForContent
#define DISPID_IAcDcContentView_GetLargeImageListForContent		DISPID_IZcDcContentView_GetLargeImageListForContent
#endif //#ifndef DISPID_IAcDcContentView_GetLargeImageListForContent

#ifndef DISPID_IAcDcContentView_GetSmallImageListForContent
#define DISPID_IAcDcContentView_GetSmallImageListForContent		DISPID_IZcDcContentView_GetSmallImageListForContent
#endif //#ifndef DISPID_IAcDcContentView_GetSmallImageListForContent

#ifndef DISPID_IAcDcContentView_Initialize
#define DISPID_IAcDcContentView_Initialize		DISPID_IZcDcContentView_Initialize
#endif //#ifndef DISPID_IAcDcContentView_Initialize

#ifndef DISPID_IAcDcContentView_InvokeCommand
#define DISPID_IAcDcContentView_InvokeCommand		DISPID_IZcDcContentView_InvokeCommand
#endif //#ifndef DISPID_IAcDcContentView_InvokeCommand

#ifndef DISPID_IAcDcContentView_IsExpandable
#define DISPID_IAcDcContentView_IsExpandable		DISPID_IZcDcContentView_IsExpandable
#endif //#ifndef DISPID_IAcDcContentView_IsExpandable

#ifndef DISPID_IAcDcContentView_NavigatorMouseUp
#define DISPID_IAcDcContentView_NavigatorMouseUp		DISPID_IZcDcContentView_NavigatorMouseUp
#endif //#ifndef DISPID_IAcDcContentView_NavigatorMouseUp

#ifndef DISPID_IAcDcContentView_NavigatorNodeClick
#define DISPID_IAcDcContentView_NavigatorNodeClick		DISPID_IZcDcContentView_NavigatorNodeClick
#endif //#ifndef DISPID_IAcDcContentView_NavigatorNodeClick

#ifndef DISPID_IAcDcContentView_NavigatorNodeCollapsing
#define DISPID_IAcDcContentView_NavigatorNodeCollapsing		DISPID_IZcDcContentView_NavigatorNodeCollapsing
#endif //#ifndef DISPID_IAcDcContentView_NavigatorNodeCollapsing

#ifndef DISPID_IAcDcContentView_NavigatorNodeExpanding
#define DISPID_IAcDcContentView_NavigatorNodeExpanding		DISPID_IZcDcContentView_NavigatorNodeExpanding
#endif //#ifndef DISPID_IAcDcContentView_NavigatorNodeExpanding

#ifndef DISPID_IAcDcContentView_PaletteBeginDrag
#define DISPID_IAcDcContentView_PaletteBeginDrag		DISPID_IZcDcContentView_PaletteBeginDrag
#endif //#ifndef DISPID_IAcDcContentView_PaletteBeginDrag

#ifndef DISPID_IAcDcContentView_PaletteColumnClick
#define DISPID_IAcDcContentView_PaletteColumnClick		DISPID_IZcDcContentView_PaletteColumnClick
#endif //#ifndef DISPID_IAcDcContentView_PaletteColumnClick

#ifndef DISPID_IAcDcContentView_PaletteItemClick
#define DISPID_IAcDcContentView_PaletteItemClick		DISPID_IZcDcContentView_PaletteItemClick
#endif //#ifndef DISPID_IAcDcContentView_PaletteItemClick

#ifndef DISPID_IAcDcContentView_PaletteItemDblClick
#define DISPID_IAcDcContentView_PaletteItemDblClick		DISPID_IZcDcContentView_PaletteItemDblClick
#endif //#ifndef DISPID_IAcDcContentView_PaletteItemDblClick

#ifndef DISPID_IAcDcContentView_PaletteMouseDown
#define DISPID_IAcDcContentView_PaletteMouseDown		DISPID_IZcDcContentView_PaletteMouseDown
#endif //#ifndef DISPID_IAcDcContentView_PaletteMouseDown

#ifndef DISPID_IAcDcContentView_PaletteMouseUp
#define DISPID_IAcDcContentView_PaletteMouseUp		DISPID_IZcDcContentView_PaletteMouseUp
#endif //#ifndef DISPID_IAcDcContentView_PaletteMouseUp

#ifndef DISPID_IAcDcContentView_PreviewMouseUp
#define DISPID_IAcDcContentView_PreviewMouseUp		DISPID_IZcDcContentView_PreviewMouseUp
#endif //#ifndef DISPID_IAcDcContentView_PreviewMouseUp

#ifndef DISPID_IAcDcContentView_QueryContextMenu
#define DISPID_IAcDcContentView_QueryContextMenu		DISPID_IZcDcContentView_QueryContextMenu
#endif //#ifndef DISPID_IAcDcContentView_QueryContextMenu

#ifndef DISPID_IAcDcContentView_Refresh
#define DISPID_IAcDcContentView_Refresh		DISPID_IZcDcContentView_Refresh
#endif //#ifndef DISPID_IAcDcContentView_Refresh

#ifndef DISPID_IAcDcContentView_ReleaseBrowser
#define DISPID_IAcDcContentView_ReleaseBrowser		DISPID_IZcDcContentView_ReleaseBrowser
#endif //#ifndef DISPID_IAcDcContentView_ReleaseBrowser

#ifndef DISPID_IAcDcContentView_RenderPreviewWindow
#define DISPID_IAcDcContentView_RenderPreviewWindow		DISPID_IZcDcContentView_RenderPreviewWindow
#endif //#ifndef DISPID_IAcDcContentView_RenderPreviewWindow

#ifndef DISPID_IAcDcContentView_SetImageLists
#define DISPID_IAcDcContentView_SetImageLists		DISPID_IZcDcContentView_SetImageLists
#endif //#ifndef DISPID_IAcDcContentView_SetImageLists

#endif //#ifndef __DCDISPID_H__
