
#ifndef __RXNAMES_H__
#define __RXNAMES_H__

#include "../inc/zrxnames.h"

#ifndef ACRX_CLASS_DICTIONARY
#define ACRX_CLASS_DICTIONARY		ZCRX_CLASS_DICTIONARY
#endif //#ifndef ACRX_CLASS_DICTIONARY

#ifndef ACRX_DYNAMIC_LINKER
#define ACRX_DYNAMIC_LINKER		ZCRX_DYNAMIC_LINKER
#endif //#ifndef ACRX_DYNAMIC_LINKER

#ifndef ACRX_KERNEL_SERVICES
#define ACRX_KERNEL_SERVICES		ZCRX_KERNEL_SERVICES
#endif //#ifndef ACRX_KERNEL_SERVICES

#ifndef ACRX_PROTOCOL_REACTOR_MANAGER
#define ACRX_PROTOCOL_REACTOR_MANAGER		ZCRX_PROTOCOL_REACTOR_MANAGER
#endif //#ifndef ACRX_PROTOCOL_REACTOR_MANAGER

#ifndef ACRX_SERVICE_DICTIONARY
#define ACRX_SERVICE_DICTIONARY		ZCRX_SERVICE_DICTIONARY
#endif //#ifndef ACRX_SERVICE_DICTIONARY

#ifndef ACRX_T
#define ACRX_T		ZCRX_T
#endif //#ifndef ACRX_T

#endif //#ifndef __RXNAMES_H__
