

#ifndef  _ZOL_ERRNO_H
#define  _ZOL_ERRNO_H

#define  OL_GOOD	0 
#define  OL_ESNVALID    1 
#define  OL_ENAMEVALID  2 
#define  OL_ESSMAX      3 
#define  OL_ESSVALID    4 
#define  OL_EBDEVALID   5 
#define  OL_EXDEVALID   6 
#define  OL_ENTSELPICK  7 
#define  OL_EEOEF       8 
#define  OL_EEOBD       9 
#define  OL_EEMPDB     10 
#define  OL_EDELVPORT  11 
#define  OL_EACQPLINE  12 
#define  OL_EHANDLE    13 
#define  OL_ENOHAND    14 
#define  OL_ETRANS     15 
#define  OL_EXSPACE    16 
#define  OL_EDELENT    17 
#define  OL_ETBLNAME   18 
#define  OL_ETBLARG    19 
#define  OL_ERDONLY    20 
#define  OL_ENONZERO   21 
#define  OL_ERANGE     22 
#define  OL_ERGBUSY    23 
#define  OL_EMMTYPE    24 
#define  OL_EMMLAY     25 
#define  OL_EMMLT      26 
#define  OL_EMMCOLOR   27 
#define  OL_EMMSTYLE   28 
#define  OL_EMMSHAPE   29 
#define  OL_EMMFTYPE   30 
#define  OL_EMODDEL    31 
#define  OL_EMODSEQ    32 
#define  OL_EMODHAND   33 
#define  OL_EMODVPVIS  34 
#define  OL_EMMLL      35 
#define  OL_EMKTYPE    36 
#define  OL_EMKPLINE   37 
#define  OL_EMKCMPLX   38 
#define  OL_EMKBNAME   39 
#define  OL_EMKBFLAG   40 
#define  OL_EMKDBNAME  41 
#define  OL_EMKNORM    42 
#define  OL_EMKNOBNM   43 
#define  OL_EMKNOBFLG  44 
#define  OL_EMKANON    45 
#define  OL_EMKBLOCK   46 
#define  OL_EMKMANDF   47 
#define  OL_EMMXDTYPE  48 
#define  OL_EMMXDNEST  49 
#define  OL_EMMXDAPPID 50 
#define  OL_EMMXDSIZE  51 
#define  OL_ENTSELNULL 52 
#define  OL_EMXDAPPID  53 
#define  OL_EMMVPORT   54 
#define  OL_INVEXT     55 
#define  OL_EFLTR1     56 
#define  OL_EFLTR2     57 
#define  OL_EFLTR3     58 
#define  OL_EFLTR4     59 
#define  OL_EFLTR5     60 
#define  OL_EFLTR6     61 
#define  OL_EFLTR7     62 
#define  OL_EFLTR8     63 
#define  OL_EFLTR9     64 
#define  OL_EFLTR10    65 
#define  OL_EFLTR11    66 
#define  OL_EFLTR12    67 
#define  OL_TABNOT     68 
#define  OL_TABNOCAL   69 
#define  OL_TABERR     70 
#define  OL_ENEWRB     71 
#define  OL_ENULLPTR   72  
#define  OL_EOPEN      73  
#define  OL_ELOADED    74  
#define  OL_EMAXAPP    75  
#define  OL_EEXEC      76 
#define  OL_EVERSION   77  
#define  OL_EDENIED    78 
#define  OL_EREFUSE    79  
#define  OL_ENOTLOADED 80  
#define  OL_ENOMEM     81 
#define  OL_EXFMVALID  82 
#define  OL_ESYMNAM    83 
#define  OL_ESYMVAL    84 
#define  OL_NONDIALOG  85

#define  OL_ECMDINP    92  
#define  OL_EBADTYPE   93  
#define  OL_EBADVPID   94  
#define  OL_EBADVIEW   95  
#define  OL_EGCODE     96  
#define  OL_EGDUP      97  
#define  OL_EBZDSSMOD  98  
#define  OL_EARGMATCH  99  
#define  OL_SVRECURSE  100 
#define  OL_MODOPEN    101 
#define  OL_NOTENTITY  102 
#define  OL_BADPLMOD   103 
#define  OL_BADCTLSTR  104 
#define  OL_EXDICT_PR  105 

#define  MAX_OL_ERRNO  105 

#endif
