#ifndef  ATILVERSIONS_H
#define  ATILVERSIONS_H

#include "../inc/ZtilVersions.h "


#ifndef ATILIMAGEAPIMAJORVERSION
#define ATILIMAGEAPIMAJORVERSION    ZTILIMAGEAPIMAJORVERSION
#endif //#ifndef ATILIMAGEAPIMAJORVERSION

#ifndef ATILIMAGEAPIMIMORVERSION
#define ATILIMAGEAPIMIMORVERSION    ZTILIMAGEAPIMIMORVERSION
#endif //#ifndef ATILIMAGEAPIMIMORVERSION

#ifndef ATILSUBSYSTEMAPIMAJORVERSION
#define ATILSUBSYSTEMAPIMAJORVERSION    ZTILSUBSYSTEMAPIMAJORVERSION
#endif //#ifndef ATILSUBSYSTEMAPIMAJORVERSION

#ifndef ATILSUBSYSTEMAPIMINORVERSION
#define ATILSUBSYSTEMAPIMINORVERSION    ZTILSUBSYSTEMAPIMINORVERSION
#endif //#ifndef ATILSUBSYSTEMAPIMINORVERSION

#ifndef ATILFORMATCODECAPIMAJORVERSION
#define ATILFORMATCODECAPIMAJORVERSION    ZTILFORMATCODECAPIMAJORVERSION
#endif //#ifndef ATILFORMATCODECAPIMAJORVERSION

#ifndef ATILFORMATCODECAPIMINORVERSION
#define ATILFORMATCODECAPIMINORVERSION    ZTILFORMATCODECAPIMINORVERSION
#endif //#ifndef ATILFORMATCODECAPIMINORVERSION

#endif
